block_app:
  target:
    entity:
      integration: family_safety
  fields:
    name:
      required: True
      selector:
        text:
          multiline: False
unblock_app:
  target:
    entity:
      integration: family_safety
  fields:
    name:
      required: True
      selector:
        text:
          multiline: False
