  # - platform: homeassistant
  #   name: "Is it nighttime From Home Assistant"
  #   entity_id: binary_sensor.nighttime
  #   id: isnight

  # - platform: status
  #   name: ${device_name}-status
  #   device_class: connectivity