clear_cache:
  name: "Clear Cache"
  description: "Removes all locally cached TTS audio files created from Chime TTS"

say:
  name: "Say"
  description: "Play an audio file before TTS audio"
  target:
    entity:
      domain: media_player
      supported_features:
        - media_player.MediaPlayerEntityFeature.PLAY_MEDIA
  fields:
    chime_path:
      name: "Chime Path"
      description: "A preset or custom audio file to be played before TTS audio"
      example: "custom_components/chime_tts/mp3s/bells.mp3"
      default: ""
      required: false
      selector:
        select:
          multiple: false
          custom_value: true
          mode: dropdown
          options:
            - label: "Bells"
              value: "custom_components/chime_tts/mp3s/bells.mp3"
            - label: "Bells 2"
              value: "custom_components/chime_tts/mp3s/bells_2.mp3"
            - label: "Bright"
              value: "custom_components/chime_tts/mp3s/bright.mp3"
            - label: "Chirp"
              value: "custom_components/chime_tts/mp3s/chirp.mp3"
            - label: "Choir"
              value: "custom_components/chime_tts/mp3s/choir.mp3"
            - label: "Chord"
              value: "custom_components/chime_tts/mp3s/chord.mp3"
            - label: "Classical"
              value: "custom_components/chime_tts/mp3s/classical.mp3"
            - label: "Ding Dong"
              value: "custom_components/chime_tts/mp3s/ding_dong.mp3"
            - label: "Drum Roll"
              value: "custom_components/chime_tts/mp3s/drumroll.mp3"
            - label: "Dun dun DUUUN!"
              value: "custom_components/chime_tts/mp3s/dun_dun_dun.mp3"
            - label: "Error"
              value: "custom_components/chime_tts/mp3s/error.mp3"
            - label: "Glockenspiel"
              value: "custom_components/chime_tts/mp3s/glockenspiel.mp3"
            - label: "Hail"
              value: "custom_components/chime_tts/mp3s/hail.mp3"
            - label: "Marimba"
              value: "custom_components/chime_tts/mp3s/marimba.mp3"
            - label: "Mario Coin"
              value: "custom_components/chime_tts/mp3s/mario_coin.mp3"
            - label: "Microphone Tap"
              value: "custom_components/chime_tts/mp3s/microphone_tap.mp3"
            - label: "Ta-da!"
              value: "custom_components/chime_tts/mp3s/tada.mp3"
            - label: "Toast"
              value: "custom_components/chime_tts/mp3s/toast.mp3"
            - label: "Twenty Four"
              value: "custom_components/chime_tts/mp3s/twenty_four.mp3"
            - label: "Sad Trombone"
              value: "custom_components/chime_tts/mp3s/sad_trombone.mp3"
            - label: "Whistle"
              value: "custom_components/chime_tts/mp3s/whistle.mp3"
    end_chime_path:
      name: "End Chime Path"
      description: "A preset or custom audio file to be played after TTS audio"
      example: "custom_components/chime_tts/mp3s/tada.mp3"
      default: ""
      required: false
      selector:
        select:
          multiple: false
          custom_value: true
          mode: dropdown
          options:
            - label: "Bells"
              value: "custom_components/chime_tts/mp3s/bells.mp3"
            - label: "Bells 2"
              value: "custom_components/chime_tts/mp3s/bells_2.mp3"
            - label: "Bright"
              value: "custom_components/chime_tts/mp3s/bright.mp3"
            - label: "Chirp"
              value: "custom_components/chime_tts/mp3s/chirp.mp3"
            - label: "Choir"
              value: "custom_components/chime_tts/mp3s/choir.mp3"
            - label: "Chord"
              value: "custom_components/chime_tts/mp3s/chord.mp3"
            - label: "Classical"
              value: "custom_components/chime_tts/mp3s/classical.mp3"
            - label: "Ding Dong"
              value: "custom_components/chime_tts/mp3s/ding_dong.mp3"
            - label: "Drum Roll"
              value: "custom_components/chime_tts/mp3s/drumroll.mp3"
            - label: "Dun dun DUUUN!"
              value: "custom_components/chime_tts/mp3s/dun_dun_dun.mp3"
            - label: "Error"
              value: "custom_components/chime_tts/mp3s/error.mp3"
            - label: "Glockenspiel"
              value: "custom_components/chime_tts/mp3s/glockenspiel.mp3"
            - label: "Hail"
              value: "custom_components/chime_tts/mp3s/hail.mp3"
            - label: "Marimba"
              value: "custom_components/chime_tts/mp3s/marimba.mp3"
            - label: "Mario Coin"
              value: "custom_components/chime_tts/mp3s/mario_coin.mp3"
            - label: "Microphone Tap"
              value: "custom_components/chime_tts/mp3s/microphone_tap.mp3"
            - label: "Ta-da!"
              value: "custom_components/chime_tts/mp3s/tada.mp3"
            - label: "Toast"
              value: "custom_components/chime_tts/mp3s/toast.mp3"
            - label: "Twenty Four"
              value: "custom_components/chime_tts/mp3s/twenty_four.mp3"
            - label: "Sad Trombone"
              value: "custom_components/chime_tts/mp3s/sad_trombone.mp3"
            - label: "Whistle"
              value: "custom_components/chime_tts/mp3s/whistle.mp3"
    delay:
      name: Delay
      description: "Delay (ms) between the chime/s and the TTS message"
      example: 450
      required: false
      default: 450
      selector:
        number:
          mode: box
          min: 0
          max: 10000
          step: 1
          unit_of_measurement: ms
    final_delay:
      name: Final Delay
      description: "Final delay (ms) added to the end of the audio"
      example: 100
      required: false
      default: 0
      selector:
        number:
          mode: box
          min: 0
          max: 10000
          step: 1
          unit_of_measurement: ms
    message:
      name: Message
      description: "Text converted into TTS audio"
      example: "Hello world!"
      required: true
      selector:
        text:
    tts_platform:
      name: "TTS Platform"
      description: "TTS platform used to generate TTS audio"
      example: "google_translate"
      required: true
      selector:
        select:
          multiple: false
          custom_value: true
          mode: dropdown
          options:
            - label: "Amazon Polly"
              value: "amazon_polly"
            - label: "Baidu"
              value: "baidu"
            - label: "Google Cloud"
              value: "google_cloud"
            - label: "Google Translate"
              value: "google_translate"
            - label: "IBM Watson TTS"
              value: "watson_tts"
            - label: "MaryTTS"
              value: "marytts"
            - label: "Microsoft Text-to-Speech (TTS)"
              value: "microsoft"
            - label: "Nabu Casa Cloud TTS"
              value: "cloud"
            - label: "Pico TTS"
              value: "picotts"
            - label: "Piper"
              value: "tts.piper"
            - label: "VoiceRSS"
              value: "voicerss"
            - label: "Yandex TTS"
              value: "yandextts"
    tts_playback_speed:
      name: TTS Playback Speed
      description: "Playback speed of the TTS audio, between 100% - 200%"
      example: 125
      required: false
      default: 100
      selector:
        number:
          mode: slider
          min: 100
          max: 200
          step: 5
          unit_of_measurement: '%'
    volume_level:
      name: Volume Level
      description: "The volume to use when playing audio"
      required: false
      default: 1.0
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.01
          mode: slider
      example: 0.75
    join_players:
      name: Join Players
      description: "Play the audio simultaneously on media_players (that support speaker groups)"
      example: "True"
      required: false
      selector:
        boolean:
    cache:
      name: Cache
      description: "Whether or not to save the generated audio file in a local cache"
      example: "True"
      required: false
      selector:
        boolean:
    announce:
      name: Announce
      description: "Stops current media during the announcement and then resume (on supported devices)"
      example: "True"
      required: false
      selector:
        boolean:
    language:
      name: Language
      description: "The TTS language (suppored by Google Translate and Nabu Casa Cloud TTS)"
      example: "'en' (for Google Translate) or 'en-US' (for Nabu Casa Cloud TTS)"
      required: false
      selector:
        text:
    tld:
      name: TLD
      description: "The dialect Domain (suppored by Google Translate)"
      example: "com.uk"
      required: false
      selector:
        select:
          options:
            - label: com
              value: com
            - label: co.uk
              value: co.uk
            - label: com.au
              value: com.au
            - label: ca
              value: ca
            - label: co.in
              value: co.in
            - label: ie
              value: ie
            - label: co.za
              value: co.za
            - label: fr
              value: fr
            - label: com.br
              value: com.br
            - label: pt
              value: pt
            - label: es
              value: es
    gender:
      name: Gender
      description: "Use a male or female voice (Nabu Casa)"
      example: "'male' or 'female'"
      required: false
      selector:
        select:
          options:
            - label: "Male"
              value: "male"
            - label: "Female"
              value: "female"