- id: '1587503984484'
  alias: tautulli_webhook
  description: ''
  trigger:
  - platform: webhook
    webhook_id: call_tautulli_webhook
  condition: []
  action:
  - data_template:
      message: '{{ trigger.json.text }}'
    service: persistent_notification.create
- id: '1594322479253'
  alias: Perform Full Backup
  description: ''
  trigger:
  - at: 02:30:00
    platform: time
  condition: []
  action:
  - data_template:
      backup_path: /share/srv
      keep_days: 28
      name: 'WeeklyBackup: {{ now().strftime(''''%A, %B %-d, %Y'''') }}'
    service: auto_backup.snapshot_full
- id: '1609788406791'
  alias: on_turn_off_reciever_turn_on_bed_c_fridge
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.yamaha_reciever_state
    - media_player.yamaha_rx_v777_reciever_integration_bed_c
    from: 'on'
    to: 'off'
    id: dfsdfsdewwer21
  condition: []
  action:
  - type: turn_on
    device_id: 6f37a034cb0c0dcefa7c4a92426c9912
    entity_id: switch.zigbee_plug_fridge_bed_c
    domain: switch
  mode: single
- id: '1609788662612'
  alias: on_turn_on_reciever_turn_off_bed_c_fridge_and_light
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.yamaha_reciever_state
    - media_player.yamaha_rx_v777_reciever_integration_bed_c
    from: 'off'
    to: 'on'
    id: 345343gges4
  condition: []
  action:
  - type: turn_off
    device_id: 6f37a034cb0c0dcefa7c4a92426c9912
    entity_id: switch.zigbee_plug_fridge_bed_c
    domain: switch
  - type: turn_off
    device_id: ecdc93708d2afbf8f645e3eb84d0e39c
    entity_id: light.bed_c_light_1
    domain: light
  mode: single
- id: '1616842943101'
  alias: on_open_garage_door_turn_on_garage_light
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 160cd6a105801adbbfb089390d7ad0ae
    entity_id: binary_sensor.zigbee_door_sensor_garage_contact
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: 376a2d183b5132bd8417b81b10aa763f
    entity_id: light.zigbee_bulb_garage
    domain: light
    brightness_pct: 100
  mode: single
- id: '1617175491057'
  alias: on_close_garage_door_turn_off_garage_light_after_10_minutes
  description: ''
  trigger:
  - type: not_opened
    platform: device
    device_id: 160cd6a105801adbbfb089390d7ad0ae
    entity_id: binary_sensor.zigbee_door_sensor_garage_contact
    domain: binary_sensor
    for:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: 376a2d183b5132bd8417b81b10aa763f
    entity_id: light.zigbee_bulb_garage
    domain: light
  mode: single
- id: '1618338665195'
  alias: Doorbell - Notify Alexa and or Google and send camera snapshot to app
  description: ''
  use_blueprint:
    path: seamus65/doorbell-notify-alexa-and-or-google-and-send-camera-snapshot-to-app.yaml
    input:
      notification_message: There is Somebody at the Door!
      doorbell: binary_sensor.doorbell_g4_doorbell
      camera: camera.uvc_g4_doorbell
      delay: 2
      notification_title: There is Somebody at the Door!
      message: There is Somebody at the Door
      echo_device: media_player.amazon_echo_dot_bed_c_alexa_integration, media_player.amazon_echo_spot_bed_a_alexa_integration,
        media_player.bed_b_echo_plus, media_player.kevin_s_echo_dot, media_player.kevin_s_echo_show
      is_ios: false
      notify_device: 6d1911bfb63c42e5fcb8f060ea3443f0
- id: '1624743776933'
  alias: on_open_front_door_turn_on_bottom_hallway_light
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: bfb5f733e3cc226de9ff83eaf5571ab9
    entity_id: binary_sensor.zigbee_door_sensor_front_contact
    domain: binary_sensor
    id: '263813'
    for:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  condition:
  - condition: state
    entity_id: binary_sensor.nighttime
    state: 'on'
  action:
  - type: turn_on
    device_id: 707639a037c05f21cb7ba1e119538bf0
    entity_id: light.shelly1l_hallway_bottom_light_1
    domain: light
  mode: single
- id: '1631736153340'
  alias: Back Lights on when Motion Detected
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: a41beba7d038fb84cb5f9b81cfe4d189
    entity_id: binary_sensor.back_g3_flex_motion
    domain: binary_sensor
    id: '351179'
  condition:
  - condition: state
    entity_id: binary_sensor.nighttime
    state: 'on'
  action:
  - type: turn_on
    device_id: d4aabe0c259eb8f64a5080976888b8a4
    entity_id: light.tybf82abce93da177c79kymc
    domain: light
    brightness_pct: 100
  - service: automation.trigger
    target:
      entity_id: automation.turn_on_garage_light_when_the_garage_door_is_opened
    data: {}
  - delay:
      minutes: 12
  - service: automation.trigger
    target:
      entity_id: automation.turn_back_light_off_if_not_activated_by_script
    data: {}
  - service: automation.trigger
    target:
      entity_id:
      - automation.turn_off_garage_light_10_mins_after_garage_door_shut
    data: {}
  mode: restart
- id: '1639344975319'
  alias: alert_when_front_door_open
  description: Raise an alert for 5 seconds when the front door is opened
  trigger:
  - type: opened
    platform: device
    device_id: bfb5f733e3cc226de9ff83eaf5571ab9
    entity_id: binary_sensor.zigbee_door_sensor_front_contact
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 0
    id: 3434xcgcg657456f5d90
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.front_door_open
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.front_door_open
    data: {}
  mode: restart
- id: '1639347854414'
  alias: alert_when_back_door_open
  description: set an input_boolean for 5 seconds when the back door is opened
  trigger:
  - type: opened
    platform: device
    device_id: a2469c4f16cd3a40ffb763fb0f349799
    entity_id: binary_sensor.zigbee_door_sensor_back_contact
    domain: binary_sensor
    id: 3434xcgcg657456ff56
  condition: []
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.back_door_open
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.back_door_open
    data: {}
  mode: restart
- id: '1639348115728'
  alias: alert_when_doorbell_rung
  description: Raise an alert for 5 seconds when the doorbell is rung
  trigger:
  - platform: state
    entity_id:
    - sensor.doorbell_g4_last_doorbell_ring
  condition: []
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.doorbell_rung
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.doorbell_rung
    data: {}
  mode: restart
- id: '1666811718812'
  alias: on_start_create_group.all_fans_binary_sensors
  description: Uses python script create_entity_groups to create an entity group
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: python_script.create_entity_groups
    data:
      domain: fan
      group: all_fans
      icon: mdi:fan
  mode: single
- id: '1666812613473'
  alias: on_start_create_group.all_entities
  description: Uses python script create_entity_groups to create an entity group
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: python_script.create_entity_groups
    data:
      domain: all
      group: all_entities
      icon: mdi:arrow-expand-all
  mode: single
- id: '1666812617895'
  alias: on_start_create_group.all_lights_binary_sensors
  description: Uses python script create_entity_groups to create an entity group
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: python_script.create_entity_groups
    data:
      domain: light
      group: all_lights
      icon: mdi:lightbulb-alert-outline
  mode: single
- id: '1666812616338'
  alias: on_start_create_group.all_zones_binary_sensors
  description: Uses python script create_entity_groups to create an entity group
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: python_script.create_entity_groups
    data:
      domain: zone
      group: all_zones
      icon: mdi:map-marker
  mode: single
- id: '1666812616938'
  alias: on_start_create_group.all_updates_binary_sensors
  description: Uses python script create_entity_groups to create an entity group
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: python_script.create_entity_groups
    data:
      domain: update
      group: all_updates
      icon: mdi:update
  mode: single
- id: '1666812616259'
  alias: on_start_create_group.all_camera_binary_sensors
  description: Uses python script create_entity_groups to create an entity group
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: python_script.create_entity_groups
    data:
      domain: camera
      group: all_cameras
      icon: mdi:camera
  mode: single
- id: '1629812616259'
  alias: on_start_create_group.all_media_players
  description: Uses python script create_entity_groups to create an entity group
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: python_script.create_entity_groups
    data:
      domain: media_player
      group: all_media_players
      icon: mdi:play-network-outline
  mode: single
- id: '1622852616259'
  alias: on_start_create_group.all_remotes_binary_sensors
  description: Uses python script create_entity_groups to create an entity group
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: python_script.create_entity_groups
    data:
      domain: remote
      group: all_remotes
      icon: mdi:remote
  mode: single
- id: '1666812633820'
  alias: on_start_create_group.all_binary_sensors
  description: Uses python script create_entity_groups to create an entity group
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: python_script.create_entity_groups
    data:
      domain: binary_sensor
      group: all_binary_sensors
      icon: mdi:toggle-switch
  mode: single
- id: '1666812616320'
  alias: on_start_create_group.all_sensors
  description: Uses python script create_entity_groups to create an entity group
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: python_script.create_entity_groups
    data:
      domain: sensor
      group: all_sensors
      icon: mdi:shape-plus
  mode: single
- id: '1666817726320'
  alias: on_start_create_group.all_switches_binary_sensors
  description: Uses python script create_entity_groups to create an entity group
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: python_script.create_entity_groups
    data:
      domain: switch
      group: all_switches
      icon: mdi:light-switch
  mode: single
- id: '1672906062419'
  alias: on_start_create_group.all_doors_binary_sensors
  description: Uses python script create_binary_device_class_group to create an entity
    group
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: python_script.create_binary_device_class_group
    data:
      group: all_door_binary_sensors
      icon: mdi:door
      collection_name: doors
      included_device_classes:
      - door
  mode: single
- id: '1673132278260'
  alias: on_start_create_group.all_plug_binary_sensors
  description: Uses python script create_binary_device_class_group to create an entity
    group
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: python_script.create_binary_device_class_group
    data:
      group: all_plug_binary_sensors
      icon: mdi:power-socket-uk
      collection_name: plugs
      included_device_classes:
      - plug
  mode: single
- id: '1673133770721'
  alias: on_start_create_group.all_occupancy_binary_sensors
  description: Uses python script create_binary_device_class_group to create an entity
    group
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: python_script.create_binary_device_class_group
    data:
      group: all_occupancy_binary_sensors
      icon: mdi:human-greeting
      collection_name: occupancy
      included_device_classes:
      - occupancy
      - motion
  mode: single
- id: '1673133921800'
  alias: on_start_create_group.all_safety_binary_sensors
  description: Uses python script create_binary_device_class_group to create an entity
    group
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: python_script.create_binary_device_class_group
    data:
      group: all_safety_binary_sensors
      icon: mdi:alarm-light
      collection_name: safety
      included_device_classes:
      - carbon_monoxide
      - safety
      - problem
      - smoke
  mode: single
- id: '1673133328800'
  alias: on_start_create_group.all_battery_binary_sensors
  description: Uses python script create_binary_device_class_group to create an entity
    group
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: python_script.create_binary_device_class_group
    data:
      group: all_battery_binary_sensors
      icon: mdi:battery-charging-high
      collection_name: battery
      included_device_classes:
      - battery
      - battery_charging
  mode: single
- id: '1679331701346'
  alias: on_open_front_door_set_input_datetime_timestamp
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: bfb5f733e3cc226de9ff83eaf5571ab9
    entity_id: binary_sensor.zigbee_door_sensor_front_contact
    domain: binary_sensor
  condition: []
  action:
  - service: input_datetime.set_datetime
    data:
      timestamp: '{{ now().timestamp() }}'
    target:
      entity_id: input_datetime.front_door_last_opened
  mode: single
- id: '1679336064408'
  alias: on_open_back_door_set_input_datetime_timestamp
  description: Sets a timestamp on an input_datetime that persists through reboots
    and ignores unknown and unavailable states
  trigger:
  - type: opened
    platform: device
    device_id: a2469c4f16cd3a40ffb763fb0f349799
    entity_id: binary_sensor.zigbee_door_sensor_back_contact
    domain: binary_sensor
  condition: []
  action:
  - service: input_datetime.set_datetime
    data:
      timestamp: '{{ now().timestamp() }}'
    target:
      entity_id: input_datetime.back_door_last_opened
  mode: single
- id: '1679336123379'
  alias: on_open_garage_door_set_input_datetime_timestamp
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 160cd6a105801adbbfb089390d7ad0ae
    entity_id: binary_sensor.zigbee_door_sensor_garage_contact
    domain: binary_sensor
  condition: []
  action:
  - service: input_datetime.set_datetime
    data:
      timestamp: '{{ now().timestamp() }}'
    target:
      entity_id: input_datetime.garage_door_last_opened
  mode: single
- id: '1679477945469'
  alias: on_open_front_door_trigger_icloud3_service
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: bfb5f733e3cc226de9ff83eaf5571ab9
    entity_id: binary_sensor.zigbee_door_sensor_front_contact
    domain: binary_sensor
  condition: []
  action:
  - service: device_tracker.icloud3_update
    data: {}
  mode: single
- id: '1679478945282'
  alias: on_motion_detect_bed_e_sensor_set_input_datetime_timestamp
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 645235e6ce6aa8a04cdd1ba7cbb0f7d1
    entity_id: binary_sensor.zigbee_motion_sensor_bed_e_occupancy
    domain: binary_sensor
  condition: []
  action:
  - service: input_datetime.set_datetime
    data:
      timestamp: '{{ now().timestamp() }}'
    target:
      entity_id: input_datetime.motion_sensor_bed_e_last_activity
  mode: single
- id: '1679479382853'
  alias: on_motion_detect_middle_hallway_sensor_set_input_datetime_timestamp
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 14c50654dba96b4da86bbd2c2cc736b8
    entity_id: binary_sensor.zigbee_motion_sensor_middle_hallway_occupancy_2
    domain: binary_sensor
  condition: []
  action:
  - service: input_datetime.set_datetime
    data:
      timestamp: '{{ now().timestamp() }}'
    target:
      entity_id: input_datetime.motion_sensor_front_door_stairs_last_activity
  mode: single
- id: '1679479488956'
  alias: on_motion_detect_nest_protect_bottom_occupancy_set_input_datetime_timestamp
  description: ''
  trigger:
  - type: occupied
    platform: device
    device_id: 2c2e9255799652086ba3713985659325
    entity_id: binary_sensor.nest_protect_bottom_floor_occupancy
    domain: binary_sensor
  condition: []
  action:
  - service: input_datetime.set_datetime
    data:
      timestamp: '{{ now().timestamp() }}'
    target:
      entity_id: input_datetime.nest_protect_bottom_floor_last_activity
  mode: single
- id: '1679479529157'
  alias: on_motion_detect_nest_protect_middle_occupancy_set_input_datetime_timestamp
  description: ''
  trigger:
  - type: occupied
    platform: device
    device_id: aa07ac37c5f02c8077dd28b92fe21c77
    entity_id: binary_sensor.nest_protect_middle_floor_occupancy
    domain: binary_sensor
  condition: []
  action:
  - service: input_datetime.set_datetime
    data:
      timestamp: '{{ now().timestamp() }}'
    target:
      entity_id: input_datetime.nest_protect_middle_floor_last_activity
  mode: single
- id: '1679479567960'
  alias: on_motion_detect_nest_protect_top_occupancy_set_input_datetime_timestamp
  description: ''
  trigger:
  - type: occupied
    platform: device
    device_id: 3e5a08167b4868eb6a925cbf4dbb2809
    entity_id: binary_sensor.nest_protect_top_floor_occupancy
    domain: binary_sensor
  condition: []
  action:
  - service: input_datetime.set_datetime
    data:
      timestamp: '{{ now().timestamp() }}'
    target:
      entity_id: input_datetime.nest_protect_top_floor_last_activity
  mode: single
- id: '1679694071157'
  alias: on_open_patio_door_1_set_input_datetime_timestamp
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 8636b1007be195b1d9a95bd3358d4d17
    entity_id: binary_sensor.zigbee_door_sensor_patio_1_contact
    domain: binary_sensor
  condition: []
  action:
  - service: input_datetime.set_datetime
    data:
      timestamp: '{{ now().timestamp() }}'
    target:
      entity_id: input_datetime.patio_door1_last_opened
  mode: single
- id: '1679694113832'
  alias: on_open_patio_door_2_set_input_datetime_timestamp
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 979af7d179104802e6923bf8831031d9
    entity_id: binary_sensor.zigbee_door_sensor_patio_2_contact
    domain: binary_sensor
  condition: []
  action:
  - service: input_datetime.set_datetime
    data:
      timestamp: '{{ now().timestamp() }}'
    target:
      entity_id: input_datetime.patio_door2_last_opened
  mode: single
- id: '1679694166875'
  alias: on_open_loft_ladder_set_input_datetime_timestamp
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 907dff53e57eb5a70f72977db29ec275
    entity_id: binary_sensor.zigbee_door_sensor_loft_contact
    domain: binary_sensor
  condition: []
  action:
  - service: input_datetime.set_datetime
    data:
      timestamp: '{{ now().timestamp() }}'
    target:
      entity_id: input_datetime.loft_ladder_last_opened
  mode: single
