- id: shellies_announce
  alias: Shellies Announce
  trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: /1
  action:
    service: mqtt.publish
    data:
      topic: shellies/command
      payload: announce
- id: shellies_discovery
  alias: Shellies Discovery
  mode: queued
  max: 999
  trigger:
    platform: mqtt
    topic: shellies/announce
  action:
    service: python_script.shellies_discovery
    data:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
      mode: '{{ trigger.payload_json.mode | default }}'
      discovery_prefix: homeassistant
      qos: 2
      shelly1l-F4CFA2E399DF:
        relay-0-name: Bed C Light
        force_update_sensors: true
      shelly1l-E09806AA14C7:
        relay-0-name: Bottom Hall Light
        force_update_sensors: true
- id: '1587503984484'
  alias: tautulli_webhook
  description: ''
  trigger:
  - platform: webhook
    webhook_id: call_tautulli_webhook
  condition: []
  action:
  - data_template:
      message: '{{ trigger.json.text }}'
    service: persistent_notification.create
- id: '1594322479253'
  alias: Perform Full Backup
  description: ''
  trigger:
  - at: 02:30:00
    platform: time
  condition: []
  action:
  - data_template:
      backup_path: /share/srv
      keep_days: 28
      name: 'WeeklyBackup: {{ now().strftime(''%A, %B %-d, %Y'') }}'
    service: auto_backup.snapshot_full
- id: '1594523612794'
  alias: alert when glances disk space goes below 2 percent
  description: ''
  trigger:
  - below: 2
    entity_id: sensor.glances_used_percent
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Disk space on DPC very low
    service: notify.mobile_app_kevins_iphone_8
- id: '1609788406791'
  alias: When Yamaha Reciever is Off, Turn on the Fridge
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.yamaha_reciever_state
    from: 'on'
    to: 'off'
  condition: []
  action:
  - type: turn_on
    device_id: 6f37a034cb0c0dcefa7c4a92426c9912
    entity_id: switch.0x00124b00226aa136
    domain: switch
  mode: single
- id: '1609788662612'
  alias: When Yamaha Receiver is On, turn Off the Fridge and Light
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.yamaha_reciever_state
    from: 'off'
    to: 'on'
  condition: []
  action:
  - type: turn_off
    device_id: 6f37a034cb0c0dcefa7c4a92426c9912
    entity_id: switch.0x00124b00226aa136
    domain: switch
  - type: turn_off
    device_id: 94895a7be392ab4224e422d8f6393cc5
    entity_id: switch.bed_c_light
    domain: switch
  mode: single
- id: '1616842943101'
  alias: Turn on Garage Light when the Garage Door is opened
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 160cd6a105801adbbfb089390d7ad0ae
    entity_id: binary_sensor.zigbee_door_sensor_garage_contact
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: 376a2d183b5132bd8417b81b10aa763f
    entity_id: light.zigbee_bulb_garage
    domain: light
    brightness_pct: 100
  mode: single
- id: '1617175491057'
  alias: Turn off garage light 10 mins after garage door shut
  description: ''
  trigger:
  - type: not_opened
    platform: device
    device_id: 160cd6a105801adbbfb089390d7ad0ae
    entity_id: binary_sensor.zigbee_door_sensor_garage_contact
    domain: binary_sensor
    for:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: 376a2d183b5132bd8417b81b10aa763f
    entity_id: light.zigbee_bulb_garage
    domain: light
  mode: single
- id: '1618338665195'
  alias: Doorbell - Notify Alexa and or Google and send camera snapshot to app
  description: ''
  use_blueprint:
    path: seamus65/doorbell-notify-alexa-and-or-google-and-send-camera-snapshot-to-app.yaml
    input:
      notification_message: There is Somebody at the Door!
      doorbell: binary_sensor.doorbell_uvc_g4_doorbell
      camera: camera.uvc_g4_doorbell
      notify_device: 7efaa4e5200ba2b72ab1fa14f7be8a66
      delay: 2
      notification_title: There is Somebody at the Door!
      message: There is Somebody at the Door
      echo_device: media_player.amazon_echo_dot_bed_c_alexa_integration, media_player.amazon_echo_dot_lounge_alexa_integration,
        media_player.amazon_echo_kitchen_alexa_integration, media_player.amazon_echo_spot_bed_a_alexa_integration,
        media_player.amazon_fire_tv_kitchen_alexa_integration, media_player.kevin_s_echo_show,
        media_player.kevin_s_firetvstick
- id: '1624743776933'
  alias: Turn on Bottom Hallway Light When the Front Door is opened
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: bfb5f733e3cc226de9ff83eaf5571ab9
    entity_id: binary_sensor.zigbee_door_sensor_front_door_contact
    domain: binary_sensor
  condition:
  - condition: sun
    after: sunset
    before: sunrise
  action:
  - type: turn_on
    device_id: ee8b8309176e9e06f44b48762de253b5
    entity_id: switch.bottom_hall_light
    domain: switch
  mode: single
