- id: '1587503984484'
  alias: tautulli_webhook
  description: ''
  trigger:
  - platform: webhook
    webhook_id: call_tautulli_webhook
  condition: []
  action:
  - data_template:
      message: '{{ trigger.json.text }}'
    service: persistent_notification.create
- id: '1594322479253'
  alias: Perform Full Backup
  description: ''
  trigger:
  - at: 02:30:00
    platform: time
  condition: []
  action:
  - data_template:
      backup_path: /share/srv
      keep_days: 28
      name: 'WeeklyBackup: {{ now().strftime(''%A, %B %-d, %Y'') }}'
    service: auto_backup.snapshot_full
- id: '1594523612794'
  alias: alert when glances disk space goes below 2 percent
  description: ''
  trigger:
  - below: 2
    entity_id: sensor.glances_used_percent
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Disk space on DPC very low
    service: notify.mobile_app_kevins_iphone_8
- id: '1609788406791'
  alias: When Yamaha Reciever is Off, Turn on the Fridge
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.yamaha_reciever_state
    from: 'on'
    to: 'off'
  condition: []
  action:
  - type: turn_on
    device_id: 6f37a034cb0c0dcefa7c4a92426c9912
    entity_id: switch.0x00124b00226aa136
    domain: switch
  mode: single
- id: '1609788662612'
  alias: When Yamaha Receiver is On, turn Off the Fridge and Light
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.yamaha_reciever_state
    from: 'off'
    to: 'on'
  condition: []
  action:
  - type: turn_off
    device_id: 6f37a034cb0c0dcefa7c4a92426c9912
    entity_id: switch.0x00124b00226aa136
    domain: switch
  - type: turn_off
    device_id: 94895a7be392ab4224e422d8f6393cc5
    entity_id: switch.bed_c_light
    domain: switch
  mode: single
- id: '1616842943101'
  alias: Turn on Garage Light when the Garage Door is opened
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 160cd6a105801adbbfb089390d7ad0ae
    entity_id: binary_sensor.zigbee_door_sensor_garage_contact
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: 376a2d183b5132bd8417b81b10aa763f
    entity_id: light.zigbee_bulb_garage
    domain: light
    brightness_pct: 100
  mode: single
- id: '1617175491057'
  alias: Turn off garage light 10 mins after garage door shut
  description: ''
  trigger:
  - type: not_opened
    platform: device
    device_id: 160cd6a105801adbbfb089390d7ad0ae
    entity_id: binary_sensor.zigbee_door_sensor_garage_contact
    domain: binary_sensor
    for:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: 376a2d183b5132bd8417b81b10aa763f
    entity_id: light.zigbee_bulb_garage
    domain: light
  mode: single
- id: '1618338665195'
  alias: Doorbell - Notify Alexa and or Google and send camera snapshot to app
  description: ''
  use_blueprint:
    path: seamus65/doorbell-notify-alexa-and-or-google-and-send-camera-snapshot-to-app.yaml
    input:
      notification_message: There is Somebody at the Door!
      doorbell: binary_sensor.doorbell_uvc_g4_doorbell
      camera: camera.uvc_g4_doorbell
      notify_device: 7efaa4e5200ba2b72ab1fa14f7be8a66
      delay: 2
      notification_title: There is Somebody at the Door!
      message: There is Somebody at the Door
      echo_device: media_player.everywhere_2
- id: '1624743776933'
  alias: Turn on Bottom Hallway Light When the Front Door is opened
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: bfb5f733e3cc226de9ff83eaf5571ab9
    entity_id: binary_sensor.zigbee_door_sensor_front_contact
    domain: binary_sensor
  condition:
  - condition: sun
    after: sunset
    before: sunrise
  action:
  - type: turn_off
    device_id: 707639a037c05f21cb7ba1e119538bf0
    entity_id: light.shelly1l_hallway_bottom_light
    domain: light
  mode: single
- id: '1628095122464'
  alias: Turn on the backdoor light when the sun sets
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - type: turn_on
    device_id: baaf4aaa5cf581b079c86f344c22832b
    entity_id: light.bf82abce93da177c79kymc
    domain: light
  mode: single
- id: '1628095252621'
  alias: Turn off backdoor light at 10 pm
  description: ''
  trigger:
  - platform: time
    at: '22:00'
  condition: []
  action:
  - type: turn_off
    device_id: baaf4aaa5cf581b079c86f344c22832b
    entity_id: light.bf82abce93da177c79kymc
    domain: light
  mode: single
