default_config:

discovery:
api:
stream:
python_script:

frontend:
  themes: !include_dir_merge_named themes

browser_mod:

recorder:
  db_url: !secret hass_addon_mariadb_url

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  packages: !include_dir_named packages

http:

logger:
  default: warning

influxdb:
  username: !secret influx_db_user
  password: !secret influx_db_pass

ffmpeg:

history:
  exclude:
    domains:
      - device_tracker
    entity_globs:
      - sensor.*_calc
      - sensor.*_timeticks
      - sensor.*_uptime

homekit:
  filter:
    include_domains:
    - climate
    - camera
    - media_player
    - person
    include_entity_globs:
    - sensor.diskstation_volume*
    - sensor.diskstation_drive_*_status
    - sensor.zigbee*
    - binary_sensor.zigbee*
    - switch.doorbell*
    - switch.harmony*
    - switch.smart_surge*
    - switch.zigbee*
    include_entities:
    - binary_sensor.remote_ui

nest:
  client_id: !secret google_oauth_client_id
  client_secret: !secret google_oauth_client_secret
  project_id: !secret nest_project_id
  subscriber_id: !secret nest_subscription_id

wake_on_lan:

device_tracker:
  - platform: luci
    host: !secret vpn_router_rj45_ip
    username: !secret luci_user
    password: !secret luci_pass
  - platform: bluetooth_tracker

notify:
  - platform: alexa_media
    name: alexa_media
  - platform: html5
    name: HTML5_popup
    vapid_pub_key: !secret google_vapid_pub_key
    vapid_prv_key: !secret google_vapid_prv_key
    vapid_email: !secret google_vapid_email

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

# media_player:
#   - platform: androidtv
#     name: "NVIDIA Shield Lounge ADB"
#     host: !secret nvidia_shield_lounge_rj45_ip
#     adbkey: "/config/.storage/androidtv_adbkey"
#     device_class: androidtv
#     # adb_server_ip: !secret ha_rj45_ip
#     # adb_server_port: 5037
#   - platform: androidtv
#     name: "NVidia Shield Bed E ADB"
#     host: !secret nvidia_shield_bede_rj45_ip
#     adbkey: "/config/.storage/androidtv_adbkey"
#     device_class: androidtv
#     # adb_server_ip: !secret ha_rj45_ip
#     # adb_server_port: 5037
#     apps:
#       #com.plexapp.mediaserver.smb: "Plex"
#       com.disney.disneyplus: "Disney+"
#       # com.plexapp.android: "Plex"
#       com.nvidia.bbciplayer: "iPlayer"
#       com.pluralsight: "Pluralsight"
#       # com.google.android.youtube.tv: "YouTube"
#       # com.amazon.amazonvideo.livingroom: "Amazon Prime"
#       # com.spotify.tv.android: "Spotify"
#       air.ITVMobilePlayer: "ITV Hub"
#       com.channel5.my5: "My 5"
#       com.apple.atve.androidtv.appletv: "Apple TV"
#     #exclude_unnamed_apps: true
#   - platform: androidtv
#     name: "Amazon Firestick Bed A ADB"
#     host: !secret amazon_fire_stick_beda_rj45_ip
#     adbkey: "/config/.storage/androidtv_adbkey"
#     device_class: firetv
#     # adb_server_ip: !secret ha_rj45_ip
#     # adb_server_port: 5037
#   - platform: androidtv
#     name: "Amazon Fire Stick Kitchen ADB"
#     host: !secret amazon_fire_stick_kitchen_rj45_ip
#     adbkey: "/config/.storage/androidtv_adbkey"
#     device_class: firetv
#     # adb_server_ip: !secret ha_rj45_ip
#     # adb_server_port: 5037

#   - platform: yamaha
#     name: "Yamaha RX-V777 Reciever Integration"
#     #unique_id: yamaha_reciever_yamaha_platform_integration
#     #entity: "yamaha_rx_v777_yamaha_network_integration"
#     host: !secret yamaha_rx_v777_rj45_ip
#     zone_ignore:
#       - zone_2
#     zone_names:
#       Main_Zone: "Bed C"
#     source_ignore:
#       - AUDIO1
#       - AUDIO2
#       - AV2
#       - AV3
#       - AV4
#       - AV5
#       - AV6
#       - Napster
#       - PHONO
#       - SERVER
#       - TUNER
#       - USB
#       - iPod (USB)
#     source_names:
#       AV1: "Nintendo Wii"
#       HDMI1: "Humax YouView"
#       HDMI2: "Apple TV 4k"
#       HDMI3: "Xbox One"
#       HDMI4: "PlayStation 3"
#       HDMI5: "Arcade Machine"
#       V-AUX: "Nintendo Switch"

lovelace_gen:
lovelace:
  mode: storage
  # Add yaml dashboards
  dashboards:
    lovelace-minimalist:
      mode: yaml
      title: Minimalist
      icon: mdi:cellphone-text
      show_in_sidebar: true
      filename: ui_lovelace_minimalist/dashboard/lovelace-minimalist.yaml
    lovelace-minimalist-network:
      mode: yaml
      title: Minimalist Network
      icon: mdi:cellphone-text
      show_in_sidebar: true
      filename: ui_lovelace_minimalist/dashboard/lovelace-minimalist-network.yaml
    lovelace-minimalist-devices:
      mode: yaml
      title: Minimalist Devices
      icon: mdi:cellphone-text
      show_in_sidebar: true
      filename: ui_lovelace_minimalist/dashboard/lovelace-minimalist-devices.yaml
    lovelace-minimalist-automation:
      mode: yaml
      title: Minimalist Automation
      icon: mdi:cellphone-text
      show_in_sidebar: true
      filename: ui_lovelace_minimalist/dashboard/lovelace-minimalist-automation.yaml
    lovelace-minimalist-security:
      mode: yaml
      title: Minimalist Security
      icon: mdi:cellphone-text
      show_in_sidebar: true
      filename: ui_lovelace_minimalist/dashboard/lovelace-minimalist-security.yaml
    lovelace-minimalist-climate:
      mode: yaml
      title: Minimalist Climate
      icon: mdi:cellphone-text
      show_in_sidebar: true
      filename: ui_lovelace_minimalist/dashboard/lovelace-minimalist-climate.yaml
    lovelace-minimalist-media:
      mode: yaml
      title: Minimalist Media
      icon: mdi:cellphone-text
      show_in_sidebar: true
      filename: ui_lovelace_minimalist/dashboard/lovelace-minimalist-media.yaml
    lovelace-minimalist-rooms:
      mode: yaml
      title: Minimalist Rooms
      icon: mdi:floor-plan
      show_in_sidebar: true
      filename: ui_lovelace_minimalist/dashboard/lovelace-minimalist-rooms.yaml