---
devices:
  - device_name: "REPL_iPhone_11"
    name: "iPhone 11:Kev"
    email: "itunes@kevinthorn.com"
  - device_name: "Julia's_iPhone_6"
    name: "iPhone 8:Ju"
    email: "julia_mailbox@kevinthorn.com"
    track_from_zone: "tudor_hall_school"
    iosapp_installed: false
  - device_name: "iPhone"
    name: "iPhone 13:Dan"
    email: "dan_thorn@icloud.com"
    track_from_zone: "dan_uni_accomodation"
    iosapp_installed: false
  - device_name: "Patrice"
    name: "iPhone 13:Emily"
    email: "emily_thorn@icloud.com"
    track_from_zone: "bloxham_school"
    iosapp_installed: false
