---
default_config:
# discovery:
stream:
python_script:
frontend:
  themes: !include_dir_merge_named "themes"
browser_mod:
recorder:
  db_url: !secret "hass_addon_mariadb_url"
  db_max_retries: 20
  db_retry_wait: 10
  # purge_keep_days: 3
  exclude:
    entities:
      - "sensor.icloud3_event_log"
group: !include "groups.yaml"
automation: !include "automations.yaml"
script: !include "scripts.yaml"
scene: !include "scenes.yaml"
homeassistant:
  customize: !include "customize.yaml"
  customize_glob: !include "customize_glob.yaml"
  packages: !include_dir_named "packages"
http:
api:
logger:
  default: "info"
  logs:
    custom_components.ui_lovelace_minimalist.base: "debug"
influxdb:
  username: !secret "influx_db_user"
  password: !secret "influx_db_pass"
ffmpeg:
history:
# exclude:
#   domains:
#     - "device_tracker"
#   entity_globs:
#     - "sensor.*_calc"
#     - "sensor.*_timeticks"
#     - "sensor.*_uptime"
wake_on_lan:
notify:
  - platform: "alexa_media"
    name: "alexa_media"
  - platform: "html5"
    name: "HTML5_popup"
    vapid_pub_key: !secret "google_vapid_pub_key"
    vapid_prv_key: !secret "google_vapid_prv_key"
    vapid_email: !secret "google_vapid_email"
lovelace_gen:
lovelace:
  mode: "storage"
  dashboards: !include "ui_lovelace_minimalist/dashboard/lovelace-dashboards.yaml"
device_tracker:
  - platform: "icloud3"
    username: !secret "apple_icloud_main_email"
    password: !secret "apple_icloud_main_password"
  # - platform: "bluetooth_tracker"
  # - platform: "bluetooth_le_tracker"
  #   track_battery: true
# device_tracker:
#   - platform: "traccar"
#     host: !secret "ha_rj45_dns"
#     port: !secret "hass_addon_traccar_port"
#     username: !secret "hass_addon_traccar_username"
#     password: !secret "hass_addon_traccar_password"
    # ssl: true
