---
default_config:
stream:
python_script:
frontend:
  themes: !include_dir_merge_named "themes"
  extra_module_url:
    - "/hacsfiles/lovelace-card-mod/card-mod.js"
browser_mod:
recorder:
  db_url: !secret "hass_addon_mariadb_url"
  db_max_retries: 20
  db_retry_wait: 10
  exclude:
    entities:
      - "sensor.icloud3_event_log"
    entity_globs:
      - "sensor.watchman*"
group: !include "groups.yaml"
automation: !include "automations.yaml"
script: !include "scripts.yaml"
scene: !include "scenes.yaml"
homeassistant:
  customize: !include "customize.yaml"
  customize_glob: !include "customize_glob.yaml"
  packages: !include_dir_named "packages"
http:
api:
zha_toolkit:
logger:
  default: "info"
  logs:
    custom_components.ui_lovelace_minimalist: "debug"
ffmpeg:
history:
wake_on_lan:
notify:
  - platform: "alexa_media"
    name: "alexa_media"
lovelace_gen:
lovelace:
  mode: "storage"
  dashboards: !include "ui_lovelace_minimalist/dashboard/lovelace-dashboards.yaml"
device_tracker:
  - platform: "icloud3"
    username: !secret "apple_icloud_main_email"
    password: !secret "apple_icloud_main_password"
