button_card_templates: !include_dir_merge_named minimalist-templates/
views:

  - title: Overview
    icon: mdi:devices
    theme: minimalist-mobile
    cards:
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: chip_back
          variables:
            ulm_chip_back_path: /lovelace-minimalist
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: custom:button-card
          template: card_navigate
          variables:
            ulm_card_navigate_path: /lovelace-minimalist-media/1
            ulm_card_navigate_title: Lounge
            ulm_card_navigate_icon: mdi:television
        - type: custom:button-card
          template: card_navigate
          variables:
            ulm_card_navigate_path: /lovelace-minimalist-media/2
            ulm_card_navigate_title: Bed A
            ulm_card_navigate_icon: mdi:bed-king
        - type: custom:button-card
          template: edge

      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: custom:button-card
          template: card_navigate
          variables:
            ulm_card_navigate_path: /lovelace-minimalist-media/3
            ulm_card_navigate_title: Bed C
            ulm_card_navigate_icon: mdi:remote-tv
        - type: custom:button-card
          template: card_navigate
          variables:
            ulm_card_navigate_path: /lovelace-minimalist-media/4
            ulm_card_navigate_title: Bed E
            ulm_card_navigate_icon: mdi:television-classic
        - type: custom:button-card
          template: edge

      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: custom:button-card
          template: card_navigate
          variables:
            ulm_card_navigate_path: /lovelace-minimalist-media/5
            ulm_card_navigate_title: Kitchen
            ulm_card_navigate_icon: mdi:fridge-outline
        - type: custom:button-card
          template: card_navigate
          variables:
            ulm_card_navigate_path: /lovelace-minimalist-media/6
            ulm_card_navigate_title: Apple TV
            ulm_card_navigate_icon: mdi:cast-variant
        - type: custom:button-card
          template: edge

  - title: Lounge
    icon: mdi:television
    theme: minimalist-mobile
    cards:
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: chip_back
          variables:
            ulm_chip_back_path: /lovelace-minimalist-media/0




        - type: vertical-stack
          cards:
            - type: button
              tap_action:
                action: navigate
                navigation_path: overview
              entity: null
              show_icon: false
              name: Back to Home
            - type: horizontal-stack
              cards:
                - type: 'custom:button-card'
                  styles:
                    icon:
                      - color: green
                    entity: switch.big_pc_unifi
                  icon: 'mdi:import'
                  show_name: false
                  tap_action:
                    action: toggle
                - type: button
                  tap_action:
                    action: none
                  show_icon: true
                  show_name: false
                  icon: 'mdi:shield'
                - type: 'custom:button-card'
                  styles:
                    icon:
                      - color: orange
                  tap_action:
                    action: toggle
                  entity: switch.big_pc_unifi
                  icon: 'mdi:power'
                  show_name: false
                  icon_height: 50px
            - type: horizontal-stack
              cards:
                - type: button
                  tap_action:
                    action: toggle
                  entity: switch.sony_tv
                  icon: 'mdi:television'
                  show_name: false
                  icon_height: 50px
                - type: 'custom:button-card'
                  styles:
                    icon:
                      - color: white
                  tap_action:
                    action: toggle
                  entity: switch.big_pc_unifi
                  icon: 'mdi:arrow-up'
                  icon_height: 50px
                  show_name: false
                - type: button
                  tap_action:
                    action: toggle
                  entity: switch.big_pc_unifi
                  show_name: false
                  icon: 'mdi:home'
                  icon_height: 50px
            - type: horizontal-stack
              cards:
                - type: 'custom:button-card'
                  styles:
                    icon:
                      - color: white
                  tap_action:
                    action: toggle
                  entity: switch.big_pc_unifi
                  icon: 'mdi:arrow-left'
                  icon_height: 50px
                  show_name: false
                - type: 'custom:button-card'
                  styles:
                    icon:
                      - color: white
                  tap_action:
                    action: toggle
                  entity: switch.big_pc_unifi
                  icon: 'mdi:arrow-all'
                  icon_height: 50px
                  show_name: false
                  hold_action:
                    action: toggle
                - type: 'custom:button-card'
                  styles:
                    icon:
                      - color: white
                  tap_action:
                    action: toggle
                  entity: switch.big_pc_unifi
                  icon: 'mdi:arrow-right'
                  icon_height: 50px
                  show_name: false
            - type: horizontal-stack
              cards:
                - type: button
                  tap_action:
                    action: toggle
                  entity: switch.big_pc_unifi
                  icon: 'mdi:undo-variant'
                  icon_height: 50px
                  show_name: false
                - type: 'custom:button-card'
                  styles:
                    icon:
                      - color: white
                  tap_action:
                    action: toggle
                  entity: switch.big_pc_unifi
                  show_name: false
                  icon: 'mdi:arrow-down'
                  icon_height: 50px
                - type: 'custom:button-card'
                  styles:
                    icon:
                      - color: red
                  tap_action:
                    action: toggle
                  entity: switch.big_pc_unifi
                  icon: 'mdi:netflix'
                  show_name: false
                  icon_height: 50px
            - type: horizontal-stack
              cards:
                - type: button
                  tap_action:
                    action: toggle
                  entity: switch.big_pc_unifi
                  show_name: false
                  icon: 'mdi:volume-plus'
                - type: button
                  tap_action:
                    action: toggle
                  entity: switch.big_pc_unifi
                  show_name: false
                  icon: 'mdi:plus'
            - type: horizontal-stack
              cards:
                - type: button
                  tap_action:
                    action: toggle
                  entity: switch.big_pc_unifi
                  icon: 'mdi:volume-minus'
                  show_name: false
                - type: button
                  tap_action:
                    action: toggle
                  entity: switch.big_pc_unifi
                  icon: 'mdi:minus'
                  show_name: false
            - type: horizontal-stack
              cards:
                - type: button
                  tap_action:
                    action: toggle
                  entity: switch.big_pc_unifi
                  show_icon: false
                  name: '1'
                - type: button
                  tap_action:
                    action: toggle
                  entity: switch.big_pc_unifi
                  show_icon: false
                  name: '2'
                  show_name: true
                - type: button
                  tap_action:
                    action: toggle
                  entity: switch.big_pc_unifi
                  show_name: true
                  show_icon: false
                  name: '3'
                  show_state: false
            - type: horizontal-stack
              cards:
                - type: button
                  tap_action:
                    action: toggle
                  entity: switch.big_pc_unifi
                  name: '4'
                  show_icon: false
                - type: button
                  tap_action:
                    action: toggle
                  entity: switch.big_pc_unifi
                  name: '5'
                  show_icon: false
                - type: button
                  tap_action:
                    action: toggle
                  entity: switch.big_pc_unifi
                  name: '6'
                  show_icon: false
            - type: horizontal-stack
              cards:
                - type: button
                  tap_action:
                    action: toggle
                  entity: switch.big_pc_unifi
                  name: '7'
                  show_icon: false
                - type: button
                  tap_action:
                    action: toggle
                  entity: switch.big_pc_unifi
                  name: '8'
                  show_icon: false
                - type: button
                  tap_action:
                    action: toggle
                  entity: switch.big_pc_unifi
                  name: '9'
                  show_icon: false
            - type: horizontal-stack
              cards:
                - type: button
                  tap_action:
                    action: toggle
                  entity: switch.big_pc_unifi
                  name: exit
                  show_icon: false
                - type: button
                  tap_action:
                    action: toggle
                  entity: switch.big_pc_unifi
                  name: '0'
                  show_icon: false
                - type: button
                  tap_action:
                    action: toggle
                  entity: switch.big_pc_unifi
                  name: teletext
                  show_icon: false
            - type: horizontal-stack
              cards:
                - type: 'custom:button-card'
                  styles:
                    icon:
                      - color: red
                  tap_action:
                    action: toggle
                  entity: switch.big_pc_unifi
                  icon: 'mdi:card'
                  show_name: false
                - type: 'custom:button-card'
                  styles:
                    icon:
                      - color: green
                  tap_action:
                    action: toggle
                  show_name: false
                  entity: switch.big_pc_unifi
                  icon: 'mdi:card'
                - type: 'custom:button-card'
                  styles:
                    icon:
                      - color: yellow
                  tap_action:
                    action: toggle
                  entity: switch.big_pc_unifi
                  icon: 'mdi:card'
                  show_name: false
                - type: 'custom:button-card'
                  styles:
                    icon:
                      - color: blue
                  tap_action:
                    action: toggle
                  entity: script.big_pc_unifi
                  icon: 'mdi:card'
                  show_name: false

  - title: Bed A
    icon: mdi:bed-king
    theme: minimalist-mobile
    cards:
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: chip_back
          variables:
            ulm_chip_back_path: /lovelace-minimalist-media/0
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
  - title: Bed C
    icon: mdi:remote-tv
    theme: minimalist-mobile
    cards:
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: chip_back
          variables:
            ulm_chip_back_path: /lovelace-minimalist-media/0
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
  - title: Bed E
    icon: mdi:television-classic
    theme: minimalist-mobile
    cards:
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: chip_back
          variables:
            ulm_chip_back_path: /lovelace-minimalist-media/0
      - type: horizontal-stack
        cards:
        - type: 'custom:button-card'
          template: card_media_player_with_control
          entity: media_player.nvidia_shield_adb_bed_e
          name: Bed E Nvidia Shield
        - type: custom:button-card
          template: edge
      - type: horizontal-stack
        cards:
        - type: 'custom:button-card'
          template: card_media_player_with_control
          entity: media_player.shield_delta
          name: Bed E Nvidia Shield
        - type: custom:button-card
          template: edge


  - title: Kitchen
    icon: mdi:fridge-outline
    theme: minimalist-mobile
    cards:
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: chip_back
          variables:
            ulm_chip_back_path: /lovelace-minimalist-media/0
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
  - title: Apple TV
    icon: mdi:cast-variant
    theme: minimalist-mobile
    cards:
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: chip_back
          variables:
            ulm_chip_back_path: /lovelace-minimalist-media/0
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge