button_card_templates: !include_dir_merge_named minimalist-templates/
views:

  - title: Security
    icon: mdi:lock
    theme: minimalist-mobile
    cards:
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: chip_back
          variables:
            ulm_chip_back_path: /lovelace-minimalist
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: card_binary_sensor_alert
          variables:
            - ulm_card_binary_sensor_alert: true
          entity: input_boolean.front_door_open
          show_last_changed: true
          name: Front
          tap_action:
            action: more-info
            entity: binary_sensor.zigbee_door_sensor_front_contact
          double_tap_action:
            action: navigate  
            navigation_path: /45df7312_zigbee2mqtt_edge
          hold_action:
            action: more-info
            entity: camera.lounge_g3_instant
        - type: 'custom:button-card'
          template: card_binary_sensor_alert
          variables:
            - ulm_card_binary_sensor_alert: true
          entity: input_boolean.back_door_open
          show_last_changed: true
          name: Back
          tap_action:
            action: more-info
            entity: binary_sensor.zigbee_door_sensor_back_contact
          double_tap_action:
            action: navigate  
            navigation_path: /45df7312_zigbee2mqtt_edge
          hold_action:
            action: more-info
            entity: camera.back_g3_flex
        - type: custom:button-card
          template: edge

      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: card_binary_sensor_alert
          variables:
            - ulm_card_binary_sensor_alert: true
          entity: binary_sensor.zigbee_door_sensor_patio_1_contact
          show_last_changed: true
          name: Patio
        - type: 'custom:button-card'
          template: card_binary_sensor_alert
          variables:
            - ulm_card_binary_sensor_alert: true
          entity: binary_sensor.zigbee_door_sensor_patio_2_contact
          show_last_changed: true
          name: Patio
        - type: custom:button-card
          template: edge

      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: card_binary_sensor
          variables:
            - ulm_card_binary_sensor_alert: true
          entity: binary_sensor.zigbee_motion_sensor_middle_hallway_occupancy
          show_last_changed: true
          name: Stairs Motion
        - type: 'custom:button-card'
          template: card_binary_sensor
          variables:
            - ulm_card_binary_sensor_alert: true
          entity: binary_sensor.motion_uvc_g3_flex_middle_hallway
          show_last_changed: true
          name: G3 Middle
        - type: custom:button-card
          template: edge

      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: card_binary_sensor
          variables:
            - ulm_card_binary_sensor_alert: true
          entity: binary_sensor.zigbee_door_sensor_garage_contact
          show_last_changed: true
          name: Garage
        - type: 'custom:button-card'
          template: card_binary_sensor
          variables:
            - ulm_card_binary_sensor_alert: false
          entity: binary_sensor.zigbee_door_sensor_bed_b_contact
          show_last_changed: true
          name: Loft
        - type: 'custom:button-card'
          template: card_binary_sensor
          variables:
            - ulm_card_binary_sensor_alert: false
          entity: binary_sensor.zigbee_door_sensor_bed_c_contact
          show_last_changed: true
          name: Bed C
        - type: custom:button-card
          template: edge

      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: card_binary_sensor
          variables:
            - ulm_card_binary_sensor_alert: true
          entity: binary_sensor.nest_protect_bottom_floor_occupancy
          show_last_changed: true
          name: Nest Bottom
        - type: 'custom:button-card'
          template: card_binary_sensor
          variables:
            - ulm_card_binary_sensor_alert: true
          entity: binary_sensor.nest_protect_middle_floor_occupancy
          show_last_changed: true
          name: Nest Middle
        - type: 'custom:button-card'
          template: card_binary_sensor
          variables:
            - ulm_card_binary_sensor_alert: true
          entity: binary_sensor.nest_protect_top_floor_occupancy
          show_last_changed: true
          name: Nest Top
        - type: custom:button-card
          template: edge

  - title: Camera's
    icon: mdi:cctv
    theme: minimalist-mobile
    # panel: true
    cards:
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: chip_back
          variables:
            ulm_chip_back_path: /lovelace-minimalist
      - type: horizontal-stack
        cards:
        - type: custom:surveillance-card
          thumb_interval: 10
          update_interval: 1
          recording_duration: 10
          show_capture_buttons: false
          cameras:
            - entity: camera.doorbell_g4
              motion_entity: binary_sensor.motion_uvc_g4_doorbell
            - entity: camera.front_g3_flex
              motion_entity: binary_sensor.motion_front_g3_flex
            - entity: camera.back_g3_flex
              motion_entity: binary_sensor.motion_uvc_g3_flex_back
            - entity: camera.lounge_g3_instant
              motion_entity: binary_sensor.motion_uvc_g3_instant
            - entity: camera.uvc_g3_flex_middle_hallway
              motion_entity: binary_sensor.motion_uvc_g3_flex_middle_hallway

  - title: Media
    icon: mdi:signal
    theme: minimalist-mobile
    cards:
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: chip_back
          variables:
            ulm_chip_back_path: /lovelace-minimalist
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: card_battery
          entity: sensor.zigbee_door_sensor_back_battery
        - type: 'custom:button-card'
          template: card_battery
          entity: sensor.zigbee_door_sensor_bed_b_battery
        - type: 'custom:button-card'
          template: card_battery
          entity: sensor.zigbee_door_sensor_bed_c_battery
        - type: custom:button-card
          template: edge

      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: card_battery
          entity: sensor.zigbee_door_sensor_front_battery
        - type: 'custom:button-card'
          template: card_battery
          entity: sensor.zigbee_door_sensor_garage_battery
        - type: 'custom:button-card'
          template: card_battery
          entity: sensor.zigbee_door_sensor_patio_1_battery
        - type: custom:button-card
          template: edge

      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: card_battery
          entity: sensor.zigbee_door_sensor_patio_2_battery
        - type: custom:button-card
          template: edge

      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: card_zigbee_lqi
          entity: sensor.zigbee_door_sensor_back_linkquality
        - type: 'custom:button-card'
          template: card_zigbee_lqi
          entity: sensor.zigbee_door_sensor_bed_b_linkquality
        - type: 'custom:button-card'
          template: card_zigbee_lqi
          entity: sensor.zigbee_door_sensor_bed_c_linkquality
        - type: custom:button-card
          template: edge

      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: card_zigbee_lqi
          entity: sensor.zigbee_door_sensor_front_linkquality
        - type: 'custom:button-card'
          template: card_zigbee_lqi
          entity: sensor.zigbee_door_sensor_garage_linkquality
        - type: 'custom:button-card'
          template: card_zigbee_lqi
          entity: sensor.zigbee_door_sensor_patio_1_linkquality
        - type: custom:button-card
          template: edge

      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: card_zigbee_lqi
          entity: sensor.zigbee_door_sensor_patio_2_linkquality
        - type: custom:button-card
          template: edge