button_card_templates: !include_dir_merge_named minimalist-templates/
views:

  - title: Lights
    icon: mdi:lightbulb
    theme: minimalist-mobile
    cards:
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: chip_back
          variables:
            ulm_chip_back_path: /lovelace-minimalist
        - type: custom:button-card
          template: edge 

      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: 'custom:button-card'
            template: card_title
            label: Bottom       
          - type: custom:button-card
            template: edge    
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
            - type: custom:button-card
              template: edge
            - type: 'custom:button-card'
              template: card_light
              entity: light.shelly1l_hallway_bottom_light_1
              name: Hallway Bottom
            - type: 'custom:button-card'
              template: card_light
              entity: light.shelly1l_study_light_1
              name: Study
            - type: custom:button-card
              template: edge
        - type: horizontal-stack
          cards:
            - type: custom:button-card
              template: edge
            - type: 'custom:button-card'
              template: card_light
              entity: light.shelly1l_lounge_light_1
              name: Lounge          
            - type: custom:button-card
              template: edge
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
            - type: custom:button-card
              template: edge
            - type: 'custom:button-card'
              template: card_light
              entity: light.shelly1l_kitchen_main_light_1
              name: Kitchen Main
            - type: 'custom:button-card'
              template: card_light
              entity: light.shelly1l_kitchen_utility_light_1
              name: Kitchen Utility
            - type: custom:button-card
              template: edge
        - type: horizontal-stack
          cards:
            - type: custom:button-card
              template: edge
            - type: 'custom:button-card'
              template: card_light
              entity: light.tybf82abce93da177c79kymc
              name: Backdoor
            - type: 'custom:button-card'
              template: card_light
              entity: light.zigbee_bulb_garage
              name: Garage
            - type: custom:button-card
              template: edge
        # - type: horizontal-stack
        #   cards:
        #     - type: custom:button-card
        #       template: edge
        #     - type: 'custom:button-card'
        #       template: card_light_slider_collapse
        #       variables:
        #         ulm_card_light_slider_collapse_name: Backdoor
        #       entity: light.tybf82abce93da177c79kymc
        #     - type: 'custom:button-card'
        #       template: card_light_slider_collapse
        #       variables:
        #         ulm_card_light_slider_collapse_name: Garage
        #       entity: light.zigbee_bulb_garage
        #     - type: custom:button-card
        #       template: edge

      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: 'custom:button-card'
            template: card_title
            label: Middle       
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: 'custom:button-card'
            template: card_light
            entity: light.shelly1l_bed_a_light_1
            name: Bed A          
          - type: 'custom:button-card'
            template: card_light
            entity: light.shelly1l_ensuite_light_1
            name: Ensuite
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: 'custom:button-card'
            template: card_light
            entity: light.shelly1l_bed_b_light_1
            name: Bed B
          - type: 'custom:button-card'
            template: card_light
            entity: light.shelly1l_bed_c_light_1
            name: Bed C
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: 'custom:button-card'
            template: card_light
            entity: light.shelly1l_bathroom_light_1
            name: Bathroom
          - type: 'custom:button-card'
            template: card_light
            entity: light.shelly1l_hallway_middle_light_1
            name: Hallway Middle
          - type: custom:button-card
            template: edge

      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: 'custom:button-card'
            template: card_title
            label: Top       
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: 'custom:button-card'
            template: card_light
            entity: light.shelly1l_bed_e_light_1
            name: Bed E          
          - type: custom:button-card
            template: edge

  - title: Electric
    icon: mdi:power-socket-uk
    theme: minimalist-mobile
    cards:
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: chip_back
          variables:
            ulm_chip_back_path: /lovelace-minimalist
        - type: custom:button-card
          template: edge 

      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: card_title
          label: Bed C       
        - type: custom:button-card
          template: edge
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: card_power_outlet
          entity: switch.0x00124b00226a8812
          name: Harmony Hub
        - type: 'custom:button-card'
          template: card_power_outlet
          entity: switch.0x00124b00226aa136
          name: Fridge
        - type: custom:button-card
          template: edge
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: card_power_outlet
          entity: switch.zigbee_plug_arcade_machine_bed_c
          name: Arcade Machine
        - type: custom:button-card
          template: edge

      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: card_title
          label: Lounge     
        - type: custom:button-card
          template: edge
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: card_power_outlet
          entity: switch.zigbee_plug_g4_doorbell_bottom_hallway
          name: Xmas Tree
        - type: custom:button-card
          template: edge

      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: card_title
          label: Garage
        - type: custom:button-card
          template: edge
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: card_power_outlet
          entity: switch.zigbee_plug_garage
          name: Garage
        - type: custom:button-card
          template: edge

  # - title: Devices
  #   icon: mdi:devices
  #   theme: minimalist-mobile
  #   cards:
  #     - type: horizontal-stack
  #       cards:
  #       - type: custom:button-card
  #         template: edge
  #       - type: 'custom:button-card'
  #         template: chip_back
  #         variables:
  #           ulm_chip_back_path: /lovelace-minimalist

  #     - type: horizontal-stack
  #       cards:
  #         - type: custom:button-card
  #           template: edge
  #         - type: 'custom:button-card'
  #           template: card_title
  #           label: Big-PC       
  #         - type: custom:button-card
  #           template: edge
  #     - type: horizontal-stack
  #       cards:
  #       - type: custom:button-card
  #         template: edge
  #       - type: 'custom:button-card'
  #         template: card_script
  #         variables: 
  #           ulm_card_script_title: Wake
  #           ulm_card_script_icon: mdi:power
  #         tap_action:
  #           action: call-service
  #           service: script.big_pc_wake
  #           service_data: 
  #             entity_id: script.big_pc_wake          
  #       - type: 'custom:button-card'
  #         template: card_script
  #         variables: 
  #           ulm_card_script_title: Reboot
  #           ulm_card_script_icon: mdi:restart
  #         tap_action:
  #           action: call-service
  #           service: script.big_pc_reboot
  #           service_data: 
  #             entity_id: script.big_pc_reboot
  #       - type: 'custom:button-card'
  #         template: card_script
  #         variables: 
  #           ulm_card_script_title: Shutdown
  #           ulm_card_script_icon: mdi:power-off
  #         tap_action:
  #           action: call-service
  #           service: script.big_pc_shutdown
  #           service_data: 
  #             entity_id: script.big_pc_shutdown

  #     - type: horizontal-stack
  #       cards:
  #         - type: custom:button-card
  #           template: edge
  #         - type: 'custom:button-card'
  #           template: card_title
  #           label: Arcade Machine
  #         - type: custom:button-card
  #           template: edge
  #     - type: horizontal-stack
  #       cards:
  #       - type: custom:button-card
  #         template: edge
  #       - type: 'custom:button-card'
  #         template: card_script
  #         variables: 
  #           ulm_card_script_title: Wake
  #           ulm_card_script_icon: mdi:power
  #         tap_action:
  #           action: call-service
  #           service: script.arcade_win10_wake
  #           service_data: 
  #             entity_id: script.arcade_win10_wake          
  #       - type: 'custom:button-card'
  #         template: card_script
  #         variables: 
  #           ulm_card_script_title: Reboot
  #           ulm_card_script_icon: mdi:restart
  #         tap_action:
  #           action: call-service
  #           service: script.arcade_win10_reboot
  #           service_data: 
  #             entity_id: script.arcade_win10_reboot
  #       - type: 'custom:button-card'
  #         template: card_script
  #         variables: 
  #           ulm_card_script_title: Shutdown
  #           ulm_card_script_icon: mdi:power-off
  #         tap_action:
  #           action: call-service
  #           service: script.arcade_win10_shutdown
  #           service_data: 
  #             entity_id: script.arcade_win10_shutdown