button_card_templates: !include_dir_merge_named minimalist-templates/
views:
  - title: Minimalist
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: title
            name: Welcome to UI-Lovelace-Minimalist
          - type: custom:button-card
            template: edge
  - title: Lights
    icon: mdi:lightbulb
    cards:

      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: 'custom:button-card'
            template: card_title
            label: Bottom       
          - type: custom:button-card
            template: edge    
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
            - type: custom:button-card
              template: edge
            - type: 'custom:button-card'
              template: card_light
              entity: light.shelly1l_hallway_bottom_light_1
              name: Hallway
            - type: custom:button-card
              template: edge          
            - type: custom:button-card
              template: edge
            - type: 'custom:button-card'
              template: card_light
              entity: light.shelly1l_study_light_1
              name: Study
            - type: custom:button-card
              template: edge
        - type: horizontal-stack
          cards:
            - type: custom:button-card
              template: edge
            - type: 'custom:button-card'
              template: card_light
              entity: light.shelly1l_lounge_light_1
              name: Lounge          
            - type: custom:button-card
              template: edge
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
            - type: custom:button-card
              template: edge
            - type: 'custom:button-card'
              template: card_light
              entity: light.shelly1l_kitchen_main_light_1
              name: Kitchen Main
            - type: custom:button-card
              template: edge
            - type: custom:button-card
              template: edge
            - type: 'custom:button-card'
              template: card_light
              entity: light.shelly1l_kitchen_utility_light_1
              name: Kitchen Utility
            - type: custom:button-card
              template: edge
        - type: horizontal-stack
          cards:
            - type: custom:button-card
              template: edge
            - type: 'custom:button-card'
              template: card_light_slider_collapse
              variables:
                ulm_card_light_slider_collapse_name: Backdoor
              entity: light.tybf82abce93da177c79kymc
            - type: custom:button-card
              template: edge
            - type: custom:button-card
              template: edge
            - type: 'custom:button-card'
              template: card_light_slider_collapse
              variables:
                ulm_card_light_slider_collapse_name: Garage
              entity: light.zigbee_bulb_garage
            - type: custom:button-card
              template: edge

      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: 'custom:button-card'
            template: card_title
            label: Middle       
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: 'custom:button-card'
            template: card_light
            entity: light.shelly1l_bed_a_light_1
            name: Bed A          
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: edge
          - type: 'custom:button-card'
            template: card_light
            entity: light.shelly1l_ensuite_light_1
            name: Ensuite
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: 'custom:button-card'
            template: card_light
            entity: light.shelly1l_bathroom_light_1
            name: Bathroom
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: edge
          - type: 'custom:button-card'
            template: card_light
            entity: light.shelly1l_bed_c_light_1
            name: Bed C
          - type: custom:button-card
            template: edge

      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: 'custom:button-card'
            template: card_title
            label: Top       
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: 'custom:button-card'
            template: card_light
            entity: light.shelly1l_bed_e_light_1
            name: Bed E          
          - type: custom:button-card
            template: edge