esphome:
  name: calex_ip_camera_01
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: "Thorn_Lounge"
  password: "Osmosis!5652"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "calex_ip_camera_01"
    password: "7GygEYCnaWNv"
    
  manual_ip:
    static_ip: 192.168.1.49
    gateway: 192.168.1.1
    subnet: 255.255.255.0

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
