esphome:
  name: rs485-iot
  comment: Industrial RS485 IoT Gateway

esp32:
  board: esp32dev

uart:
  rx_pin: 26
  tx_pin: 27
  baud_rate: 9600
  rx_buffer_size: 500000
  stop_bits: 1

sensor:
  - platform: sdm_meter
    phase_a:
      current:
        name: "SDM220M Current"
      voltage:
        name: "SDM220M Voltage"
      active_power:
        name: "SDM220M Power"
      power_factor:
        name: "SDM220M Power Factor"
      apparent_power:
        name: "SDM220M Apparent Power"
      reactive_power:
        name: "SDM220M Reactive Power"
      phase_angle:
        name: "SDM220M Phase Angle"
    frequency:
      name: "SDM220M Frequency"
    total_power:
      name: "SDM220M Total Power"
    import_active_energy:
      name: "SDM220M Import Active Energy"
    export_active_energy:
      name: "SDM220M Export Active Energy"
    import_reactive_energy:
      name: "SDM220M Import Reactive Energy"
    export_reactive_energy:
      name: "SDM220M Export Reactive Energy"
    update_interval: 60s

# uart:
#   id: mod_bus
#   tx_pin: 17
#   rx_pin: 16
#   baud_rate: 115200
#   stop_bits: 1

# modbus:
#   flow_control_pin: 5
#   id: modbus1

# modbus_controller:
#   - id: epever
#     ## the Modbus device addr
#     address: 0x1
#     modbus_id: modbus1
#     setup_priority: -10

# text_sensor:
#   - name: "rtc_clock"
#     platform: modbus_controller
#     modbus_controller_id: epever
#     id: rtc_clock
#     internal: true
#     register_type: holding
#     address: 0x9013
#     register_count: 3
#     raw_encode: HEXBYTES
#     response_size: 6

# switch:
#   - platform: modbus_controller
#     modbus_controller_id: epever
#     id: reset_to_fabric_default
#     name: "Reset to Factory Default"
#     register_type: coil
#     address: 0x15
#     bitmask: 1

# sensor:
#   - platform: modbus_controller
#     modbus_controller_id: epever
#     name: "Battery Capacity"
#     id: battery_capacity
#     register_type: holding
#     address: 0x9001
#     unit_of_measurement: "AH"
#     value_type: U_WORD