substitutions:
  device_name: shelly1l-hallway-middle
  friendly_name: Shelly Light Switch Middle Hallway
  light1_icon: "mdi:chandelier"  
  device_ip: "25"
  ssid: !secret not_wifi_ssid
  log_level: INFO  
  max_temp: "80.0" #Centigrade

# Common Include
<<: !include includes/shelly-common.yaml

# Extended Config
light:
  - platform: binary
    name: ${device_name}-light-1
    output: shelly_1l_relay
    id: lightid1
    icon: ${light1_icon}

output:
  - platform: gpio
    pin: GPIO5
    id: shelly_1l_relay

binary_sensor:
# =====================common binary_sensor
  - platform: homeassistant
    name: ${device_name}-isnight
    entity_id: binary_sensor.nighttime
    id: isnight
    internal: true

  - platform: status
    name: ${device_name}-status
    device_class: connectivity
# =====================common binary_sensor

  - platform: gpio
    pin:
      number: GPIO4
    name: ${device_name}-switch-1
    id: switchid1
    on_state:
      then:
        - light.toggle: lightid1
    on_double_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - homeassistant.service:
            service: light.turn_off
            data:
              entity_id: light.all_lights_everywhere
    filters:
      - delayed_on_off: 50ms
    
  - platform: gpio
    pin:
      number: GPIO14
    name: ${device_name}-switch-2
    id: switchid2

    # config for multi click actions
    # on_multi_click:
    #   # double click
    #   - timing:
    #       - ON for at most 1s
    #       - OFF for at most 1s
    #       - ON for at most 1s
    #       - OFF for at least 0.2s
    #     then:
    #       - if:
    #           condition:
    #             and:
    #               - wifi.connected:
    #               - api.connected:
    #           # send double click event in case wifi and api are conncected
    #           then:
    #             - homeassistant.event:
    #                 event: esphome.button_pressed
    #                 data:
    #                   title: ${device_name}-double-click
    #           # toggle relay in case either wifi or api are not connected
    #           else:
    #             - light.toggle: lightid 