---
substitutions:
  device_name: "shelly_1l_kitchen_utility"
  friendly_name: "Shelly Light Switch Kitchen Utility and Backdoor"
  light1_icon: "mdi:ceiling-light"
  light2_icon: "mdi:coach-lamp"
  device_ip: "13"
  ssid: !secret "not_wifi_ssid"
  log_level: "INFO"
  max_temp: "80.0"  # Centigrade

# Common Include
<<: !include "includes/shelly_1l_common.yaml"

# Extended Config
light:
  - platform: "binary"
    name: "${device_name}_light_1"
    output: "${device_name}_shellyrelay1"
    id: "${device_name}_lightid1"
    icon: "${light1_icon}"

  - platform: "binary"
    name: "${device_name}_light_2"
    output: "ha_script"
    id: "lightid2"
    icon: "${light2_icon}"

output:
  - platform: "gpio"
    pin: "GPIO5"
    id: "${device_name}_shellyrelay1"

  - platform: "template"
    type: "binary"
    id: "ha_script"
    write_action:
      then:
        - homeassistant.service:
            service: "script.back_door_light_toggle"

binary_sensor:
  # =====================common binary_sensor
  - platform: "status"
    name: "${device_name}_status"
    device_class: "connectivity"
    filters:
      - delayed_off: "5min"
  # =====================common binary_sensor

  - platform: "gpio"
    pin:
      number: "GPIO4"
    name: "${device_name}_switch_1"
    id: "${device_name}_switchid1"
    on_state:
      then:
        - light.toggle: "${device_name}_lightid1"
    filters:
      - delayed_on_off: "50ms"

  - platform: "gpio"
    pin:
      number: "GPIO14"
    name: "${device_name}_switch_2"
    on_state:
      then:
        - light.toggle: "lightid2"
    id: "${device_name}_switchid2"
