---
substitutions:
  device_name: "shellykitchenmain"
  friendly_name: "Kitchen Main Light"
  area: "kitchen"
  light1_icon: "mdi:light-recessed"
#  light2_icon: "mdi:lightbulb-fluorescent-tube"
  device_ip: "14"
  ssid: !secret "not_wifi_ssid"
  log_level: "DEBUG"
  max_temp: "80.0"  # Centigrade

# Common Include
<<: !include "includes/shelly_1l_common.yaml"

# Extended Config - only use when overwriting values in include
# Note: the entire light and binary_sensor blocks will be overwritten
