load_pages:
  name: Load pages.jsonl
  description: Loads new design from pages.jsonl file from full path. The file must be located in an authorised location defined by allowlist_external_dirs in Home Assistant's main configuration.
  target:
  fields:
    path:
      name: Path
      description: Path to the file containing the plate layout in JSONL format
      required: true
      example: "/config/pages.jsonl"
      selector:
        text:

wakeup:
  name: Wakeup
  description: This is helpful e.g. when you want to wake up the display when an external event has occurred, like a presence or PIR motion sensor.
  target:

next_page:
  name: Next Page
  description: Changes plate to the next page
  target:

prev_page:
  name: Previous Page
  description: Changes plate to the previous page
  target:

clear_page:
  name: Clear Page
  description: Clears the contents of the specified page number.
  target:
  fields:
    page:
      name: Page
      description: Page number to clear (if not specified, clear all pages)
      required: false
      selector:
        number:
          min: 1
          max: 12

change_page:
  name: Change Page
  description: Changes plate directly to the specified page number.
  target:
  fields:
    page:
      name: Page
      description: Page number to change to
      required: true
      selector:
        number:
          min: 1
          max: 12
