---
binary_sensor:
  - platform: "template"
    sensors:
      apple_tv_bed_c_state:
        friendly_name: "Apple TV Bed C State"
        unique_id: "binary_state_apple_tv_bed_c"
        icon_template: "mdi:television-play"
        value_template: >-
          {% if states('media_player.amazon_fire_tv_kitchen_adb') == 'unknown' or
            states('media_player.amazon_fire_tv_kitchen_adb') == 'unavailable' or
            states('media_player.amazon_fire_tv_kitchen_adb') == 'off' %}
              {{ "off" }}
          {% else %}
              {{ "on" }}
          {% endif %}

  - platform: "template"
    sensors:
      fire_stick_tv_kitchen_state:
        friendly_name: "Fire TV Kitchen State"
        unique_id: "binary_state_fire_tv_kitchen"
        icon_template: "mdi:television-play"
        device_class: "power"
        value_template: >-
          {% if states('media_player.amazon_fire_tv_kitchen_adb') == 'unknown' or
            states('media_player.amazon_fire_tv_kitchen_adb') == 'unavailable' or
            states('media_player.amazon_fire_tv_kitchen_adb') == 'off' %}
              {{ "off" }}
          {% else %}
              {{ "on" }}
          {% endif %}

  - platform: "template"
    sensors:
      fire_stick_tv_bed_a_state:
        friendly_name: "Fire TV Bed A State"
        unique_id: "binary_state_fire_tv_bed_a"
        icon_template: "mdi:television-play"
        value_template: >-
          {% if (states('device_tracker.samsung_ue32f4500_tv_unifi') == 'unknown' or
            states('device_tracker.samsung_ue32f4500_tv_unifi') == 'unavailable' or
            states('device_tracker.samsung_ue32f4500_tv_unifi') == 'away' or
            states('device_tracker.samsung_ue32f4500_tv_unifi') == 'not_home'or
            states('device_tracker.samsung_ue32f4500_tv_unifi') == 'off') and
            (states('media_player.amazon_firestick_bed_a_adb') == 'unknown' or
            states('media_player.amazon_firestick_bed_a_adb') == 'unavailable' or
            states('media_player.amazon_firestick_bed_a_adb') == 'off') %}
              {{ "off" }}
          {% else %}
              {{ "on" }}
          {% endif %}

  - platform: "template"
    sensors:
      nvidia_shield_lounge_state:
        friendly_name: "NVidia Shield Lounge State"
        unique_id: "binary_state_shield_lounge"
        icon_template: "mdi:television-play"
        value_template: >-
          {% if (states('device_tracker.samsung_ue48hu7500t_tv_unifi') == 'unknown' or
            states('device_tracker.samsung_ue48hu7500t_tv_unifi') == 'unavailable' or
            states('device_tracker.samsung_ue48hu7500t_tv_unifi') == 'away' or
            states('device_tracker.samsung_ue48hu7500t_tv_unifi') == 'not_home'or
            states('device_tracker.samsung_ue48hu7500t_tv_unifi') == 'off') and
            (states('media_player.nvidia_shield_adb_lounge') == 'unknown' or
            states('media_player.nvidia_shield_adb_lounge') == 'unavailable' or
            states('media_player.nvidia_shield_adb_lounge') == 'off') %}
              {{ "off" }}
          {% else %}
              {{ "on" }}
          {% endif %}

  - platform: "template"
    sensors:
      nvidia_shield_bed_e_state:
        friendly_name: "NVidia Shield Bed E State"
        unique_id: "binary_state_shield_bed_e"
        icon_template: "mdi:television-play"
        value_template: >-
          {% if states('media_player.nvidia_shield_adb_bed_e') == 'unknown' or
            states('media_player.nvidia_shield_adb_bed_e') == 'unavailable' or
            states('media_player.nvidia_shield_adb_bed_e') == 'off' %}
              {{ "off" }}
          {% else %}
              {{ "on" }}
          {% endif %}

  - platform: "template"
    sensors:
      harmony_hub_bed_c_state:
        friendly_name: "Harmony Hub Bed C State"
        unique_id: "binary_state_harmony_hub_bed_c"
        icon_template: "mdi:television-play"
        value_template: >-
          {% if states('remote.harmony_hub') == 'unknown' or
            states('remote.harmony_hub') == 'unavailable' or
            states('remote.harmony_hub') == 'off' %}
              {{ "off" }}
          {% else %}
              {{ "on" }}
          {% endif %}

  # - platform: "template"
  #   sensors:
  #     yamaha_reciever_state:
  #       friendly_name: "Yamaha Reciever State"
  #       unique_id: "devicetracker_yamaha_reciever_state"
  #       value_template: "{{ is_state('media_player.rx_v777_reciever_yamaha_integration_bed_c', 'on') }}"
  #       icon_template: "mdi:audio-video"

  # - platform: "template"
  #   sensors:
  #     is_kev_driving:
  #       friendly_name: "Kev Driving State"
  #       unique_id: "binary_state_is_kev_driving"
  #       value_template: "{{ is_state('sensor.iphone_activity', 'automotive') }}"
  #       icon_template: "mdi:train-car"
  #       device_class: "moving"

  # - platform: "template"
  #   sensors:
  #     back_g3_flex_occupancy:
  #       friendly_name: "Back G3 Flex Occupancy"
  #       unique_id: "binary_state_back_g3_flex_occupancy"
  #       value_template: "{{ (((as_timestamp(utcnow().isoformat()) | round) / 60) - ((as_timestamp(states('sensor.back_g3_flex_last_motion_detected')) | round) / 60)) | round > 20 }}"
  #       icon_template: "mdi:cctv"
  #       device_class: "occupancy"

  # bed_c_g3_instant_occupancy:
  #   name: "Bed C G3 Instant Occupancy"
  #   icon: "phu:mini-camera"
  # bottom_hallway_g3_instant_occupancy:
  #   name: "Bottom Hallway G3 Instant Occupancy"
  #   icon: "phu:mini-camera"
  # doorbell_g4_occupancy:
  #   name: "Doorbell G4 Occupancy"
  #   icon: "mdi:doorbell-video"
  # front_g3_flex_occupancy:
  #   name: "Front G3 Flex Occupancy"
  #   icon: "mdi:cctv"
  # kitchen_g3_instant_occupancy:
  #   name: "Kitchen G3 Instant Occupancy"
  #   icon: "phu:mini-camera"
  # middle_hallway_g3_flex_occupancy:
  #   name: "Middle Hallway G3 Flex Occupancy"
  #   icon: "mdi:cctv"

  - platform: "tod"
    name: "nighttime"
    after: "sunset"
    before: "sunrise"
  - platform: "tod"
    name: "quiettime"
    after: "23:00"
    before: "07:00"
  - platform: "tod"
    name: "cheap heating time"
    after: "00:00"
    before: "07:00"
  - platform: "tod"
    name: "morning heating time"
    after: "06:00"
    before: "09:00"
  - platform: "tod"
    name: "afternoon heating time"
    after: "14:00"
    before: "17:00"
  - platform: "tod"
    name: "evening heating time"
    after: "19:00"
    before: "21:00"
