---
sensor:
  - platform: "integration"
    source: "sensor.usw_pro_24_poe_bed_a_laptop_poe_power"  # Watts
    name: "usw_pro_24_poe_bed_a_laptop_poe_energy"
    unique_id: "_unique_sensor_usw_pro_24_poe_bed_a_laptop_poe_energy"
    unit_prefix: "k"
    unit_time: "h"
    round: 3
  - platform: "integration"
    source: "sensor.usw_pro_24_poe_bed_a_tv_poe_power"  # Watts
    name: "usw_pro_24_poe_bed_a_tv_poe_energy"
    unique_id: "_unique_sensor_usw_pro_24_poe_bed_a_tv_poe_energy"
    unit_prefix: "k"
    unit_time: "h"
    round: 3
  - platform: "integration"
    source: "sensor.usw_pro_24_poe_bed_b_poe_power"  # Watts
    name: "usw_pro_24_poe_bed_b_poe_energy"
    unique_id: "_unique_sensor_usw_pro_24_poe_bed_b_poe_energy"
    unit_prefix: "k"
    unit_time: "h"
    round: 3
  - platform: "integration"
    source: "sensor.usw_pro_24_poe_kitchen_poe_power"  # Watts
    name: "usw_pro_24_poe_kitchen_poe_energy"
    unique_id: "_unique_sensor_usw_pro_24_poe_kitchen_poe_energy"
    unit_prefix: "k"
    unit_time: "h"
    round: 3
  - platform: "integration"
    source: "sensor.usw_pro_24_poe_loft_poe_power"  # Watts
    name: "usw_pro_24_poe_loft_poe_energy"
    unique_id: "_unique_sensor_usw_pro_24_poe_loft_poe_energy"
    unit_prefix: "k"
    unit_time: "h"
    round: 3
  - platform: "integration"
    source: "sensor.usw_pro_24_poe_lounge_right_poe_power"  # Watts
    name: "usw_pro_24_poe_lounge_right_poe_energy"
    unique_id: "_unique_sensor_usw_pro_24_poe_lounge_right_poe_energy"
    unit_prefix: "k"
    unit_time: "h"
    round: 3
  - platform: "integration"
    source: "sensor.usw_pro_24_poe_study_poe_power"  # Watts
    name: "usw_pro_24_poe_study_poe_energy"
    unique_id: "_unique_sensor_usw_pro_24_poe_study_poe_energy"
    unit_prefix: "k"
    unit_time: "h"
    round: 3
  - platform: "integration"
    source: "sensor.usw_flex_loft_ap_top_poe_power"  # Watts
    name: "usw_flex_loft_ap_top_poe_energy"
    unique_id: "_unique_sensor_usw_flex_loft_ap_top_poe_energy"
    unit_prefix: "k"
    unit_time: "h"
    round: 3
  - platform: "integration"
    source: "sensor.usw_flex_loft_cam_back_poe_power"  # Watts
    name: "usw_flex_loft_cam_back_poe_energy"
    unique_id: "_unique_sensor_usw_flex_loft_cam_back_poe_energy"
    unit_prefix: "k"
    unit_time: "h"
    round: 3
  - platform: "integration"
    source: "sensor.usw_flex_loft_cam_front_poe_power"  # Watts
    name: "usw_flex_loft_cam_front_poe_energy"
    unique_id: "_unique_sensor_usw_flex_loft_cam_front_poe_energy"
    unit_prefix: "k"
    unit_time: "h"
    round: 3
  - platform: "integration"
    source: "sensor.usw_flex_loft_dlpc_isolated_poe_power"  # Watts
    name: "usw_flex_loft_dlpc_isolated_poe_energy"
    unique_id: "_unique_sensor_usw_flex_loft_dlpc_isolated_poe_energy"
    unit_prefix: "k"
    unit_time: "h"
    round: 3
  - platform: "integration"
    source: "sensor.usw_lite_8port_bed_e_g3_flex_hall_poe_power"  # Watts
    name: "usw_lite_8port_bed_e_g3_flex_hall_poe_energy"
    unique_id: "_unique_sensor_usw_lite_8port_bed_e_g3_flex_hall_poe_energy"
    unit_prefix: "k"
    unit_time: "h"
    round: 3

  # SP600 plugs
  # - platform: "integration"
  #   source: "sensor.zigbee_energy_monitor_outlet_switch_washing_machine_instantaneous_demand"  # Watts
  #   name: "Washing Machine Plug Energy:Kitchen"
  #   unique_id: "_unique_sensor_washing_machine_plug_total_increasing_energy"
  #   unit_prefix: "k"
  #   unit_time: "h"
  #   round: 3
  - platform: "integration"
    source: "sensor.zigbee_energy_monitor_outlet_switch_dishwasher_instantaneous_demand"  # Watts
    name: "Dishwasher Plug Energy: Kitchen"
    unique_id: "_unique_sensor_dishwasher_plug_total_increasing_energy"
    unit_prefix: "k"
    unit_time: "h"
    round: 3

  # Tapo P110 plugs
  - platform: "integration"
    source: "sensor.fridge_kitchen_current_consumption"  # Watts
    name: "Fridge Plug Energy:Kitchen"
    unique_id: "_unique_sensor_kitchen_fridge_total_increasing_energy"
    unit_prefix: "k"
    unit_time: "h"
    round: 3
  - platform: "integration"
    source: "sensor.kettle_plug_kitchen_unifi_current_consumption"  # Watts
    name: "Kettle Plug Energy:Kitchen"
    unique_id: "_unique_sensor_kitchen_kettle_total_increasing_energy"
    unit_prefix: "k"
    unit_time: "h"
    round: 3
  - platform: "integration"
    source: "sensor.microwave_plug_kitchen_unifi_current_consumption"  # Watts
    name: "Microwave Plug Energy:Kitchen"
    unique_id: "_unique_sensor_kitchen_microwave_total_increasing_energy"
    unit_prefix: "k"
    unit_time: "h"
    round: 3
  - platform: "integration"
    source: "sensor.chest_freezer_plug_garage_unifi_current_consumption"  # Watts
    name: "Chest Freezer Plug Energy:Garage"
    unique_id: "_unique_sensor_garage_chest_freezer_total_increasing_energy"
    unit_prefix: "k"
    unit_time: "h"
    round: 3
  - platform: "integration"
    source: "sensor.fridge_freezer_plug_garage_unifi_current_consumption"  # Watts
    name: "Fridge/Freezer Plug Energy:Garage"
    unique_id: "_unique_sensor_garage_fridgefreezer_total_increasing_energy"
    unit_prefix: "k"
    unit_time: "h"
    round: 3
  - platform: "integration"
    source: "sensor.udm_pro_plug_bed_c_unifi_current_consumption"  # Watts
    name: "UDM Pro Plug Energy:Bed C"
    unique_id: "_unique_sensor_bed_c_udm_pro_total_increasing_energy"
    unit_prefix: "k"
    unit_time: "h"
    round: 3
  - platform: "integration"
    source: "sensor.fly_killer_kitchen_unifi_current_consumption"  # Watts
    name: "Fly Killer Plug Energy:Kitchen"
    unique_id: "_unique_sensor_kitchen_fly_killer_total_increasing_energy"
    unit_prefix: "k"
    unit_time: "h"
    round: 3
