sensor:
#  - platform: darksky
#    api_key: !secret dark_sky_api
#    hourly_forecast:
#      - 2
#    monitored_conditions:
#      - summary
#      - icon
#      - precip_type
#      - precip_intensity
#      - precip_probability
#      - precip_accumulation
#      - temperature
#      - apparent_temperature
#      - dew_point
#      - wind_speed
#      - wind_gust
#      - wind_bearing
#      - cloud_cover
#      - humidity
#      - pressure
#      - visibility
#      - ozone
#      - minutely_summary
#      - hourly_summary
#      - daily_summary
#      - temperature_high
#      - temperature_low
#      - apparent_temperature_high
#      - apparent_temperature_low
#      - precip_intensity_max
#      - uv_index
#      - moon_phase
#      - sunrise_time
#      - sunset_time
#      - nearest_storm_distance
#      - nearest_storm_bearing
#      - alerts

  # Own public IPv4 address
  - platform: dnsip
    name: WAN IP

    # Kevs Phone to Home
  - platform: google_travel_time
    name: Travel Time Kevs Location To Home
#    unique_id: travel_time_kev_to_home
    api_key: !secret google_distance_matrix_api_key
    origin: person.kevin_thorn
    destination: zone.home
    scan_interval: 1200

    # Home to Tudor
  - platform: google_travel_time
    name: Travel Time Home To Tudor Hall
#    unique_id: travel_time_home_to_tudor_hall
    api_key: !secret google_distance_matrix_api_key
    origin: zone.home
    destination: zone.tudor_hall_school
    scan_interval: 1200

    # Home to Bloxham
  - platform: google_travel_time
    name: Travel Time Home To Bloxham
#    unique_id: travel_time_home_to_bloxham_school
    api_key: !secret google_distance_matrix_api_key
    origin: zone.home
    destination: zone.bloxham_school
    scan_interval: 600

  - platform: launch_library

  - platform: feedparser
    name: RSS Hass Alerts
    feed_url: 'https://alerts.home-assistant.io/feed.xml'
    date_format: '%a, %b %d %I:%M %p'
    inclusions:
      - title
      - link
      - description
      - image
      - language
      - pubDate
    exclusions:
      - language

#  - platform: opensky
#    radius: 10

  - platform: tautulli
    name: Plex State Tautulli
    host: !secret ha_ip
    api_key: !secret tautulli_api_key

  - platform: mqtt
    name: Plex State MQTT
    state_topic: homeassistant/sensor/tautulli/all
    value_template: '{{ value_json.body }}'
    unique_id: tautulli_mqtt_status

  - platform: sql
    db_url: !secret mysql_db_url
    queries:
    - name: HASS DB size
      query: !secret mysql_db_url_size_query
      column: 'value'
      unit_of_measurement: MB

  - platform: nut
    name: "APC Back-UPS 550"
    host: a0d7b954-nut
    resources:
      - battery.charge 
      - battery.charge.low 
      - battery.charge.warning 
      - battery.date 
      - battery.mfr.date 
      - battery.runtime 
      - battery.runtime.low 
      - battery.type 
      - battery.voltage 
      - battery.voltage.nominal 
#      - device.mfr 
#      - device.model 
#      - device.serial 
#      - device.type 
#      - driver.name 
#      - driver.parameter.pollfreq 
#      - driver.parameter.pollinterval 
#      - driver.parameter.port
#      - driver.version 
#      - driver.version.data
#      - driver.version.internal
      - input.sensitivity
      - input.transfer.high
      - input.transfer.low
      - input.voltage
      - input.voltage.nominal
      - ups.beeper.status
      - ups.delay.shutdown
#      - ups.firmware
#      - ups.firmware.aux
      - ups.load
#      - ups.mfr
#      - ups.mfr.date
#      - ups.model
#      - ups.productid
      - ups.realpower.nominal
#      - ups.serial 
      - ups.status
      - ups.test.result
      - ups.timer.reboot
      - ups.timer.shutdown 
#      - ups.vendorid

  - platform: blockchain
    addresses:
      - '9893d2a9-d2a9-4910-b072-ba93f7fc08da'

  - platform: bitcoin
    currency: GBP
    display_options:
      - exchangerate
      - trade_volume_btc