---
sensor:
  - platform: "feedparser"
    name: "RSS Hass Alerts"
    feed_url: "https://alerts.home-assistant.io/feed.xml"
    date_format: "%a, %b %d %I:%M %p"
    inclusions:
      - "title"
      - "link"
      - "description"
      - "image"
      - "language"
      - "pubDate"
    exclusions:
      - "language"

  - platform: "tautulli"
    name: "Plex State Tautulli"
    host: !secret "ha_rj45_ip"
    api_key: !secret "tautulli_api_key"

  - platform: "bitcoin"
    currency: "GBP"
    display_options:
      - "exchangerate"
      - "trade_volume_btc"

  - platform: "template"
    sensors:
      date_long:
        friendly_name: "Date and Day of week"
        value_template: >
          {% set months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] %}
          {% set days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"] %}
          {{ months[now().month-1] }}.{{ now().day }}th. {{ days[now().weekday()] }}

  - platform: "statistics"
    entity_id: "sensor.nvidia_shield_lounge_unifi_tx"
    name: "nvidia_shield_lounge_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.nvidia_shield_bed_e_unifi_tx"
    name: "nvidia_shield_bed_e_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.amazon_firestick_4k_rj45_unifi_tx_2"
    name: "amazon_firestick_4k_rj45_unifi_tx_2_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.amazon_firestick_4k_rj45_unifi_tx"
    name: "amazon_firestick_4k_rj45_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.apple_imac_2011_unifi_tx"
    name: "apple_imac_2011_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.apple_macbook_pro_2018_kev_unifi_tx"
    name: "apple_macbook_pro_2018_kev_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.apple_tv_4k_unifi_tx"
    name: "apple_tv_4k_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.arcade_machine_unifi_tx"
    name: "arcade_machine_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.big_pc_unifi_tx"
    name: "big_pc_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.caldigit_thunderbolt_dock_unifi_tx"
    name: "caldigit_thunderbolt_dock_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.dans_nintendo_switch_unifi_tx"
    name: "dans_nintendo_switch_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.dell_work_laptop_kev_unifi_wifi_tx"
    name: "dell_work_laptop_kev_unifi_wifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.download_pc_unifi_tx"
    name: "download_pc_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.ipad_air_4th_gen_tx"
    name: "ipad_air_4th_gen_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.kev_iphone_11_unifi_tx"
    name: "kev_iphone_11_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.home_assistant_unifi_tx"
    name: "home_assistant_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.iphone_12_dan_tx"
    name: "iphone_12_dan_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.iphone_tx_4"
    name: "iphone_tx_4_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.ju_iphone_8_unifi_tx"
    name: "ju_iphone_8_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.samsung_ue32f4500_tv_unifi_tx"
    name: "samsung_ue32f4500_tv_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.samsung_ue48hu7500t_tv_unifi_tx"
    name: "samsung_ue48hu7500t_tv_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.sony_playstation_3_unifi_tx"
    name: "sony_playstation_3_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.synology_diskstation_ds412_unifi_tx"
    name: "synology_diskstation_ds412_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.xbox_series_x_unifi_tx"
    name: "xbox_series_x_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  # modbus energy conversions
  # - platform: "integration"
  #   source: "sensor.sdm220_modbus_current_system_positive_power_demand"
  #   name: "sdm220_modbus_current_system_positive_energy_demand"
  #   unique_id: "sensor.sdm220_modbus_current_system_positive_energy_demand"
  #   unit_prefix: "k"
  #   round: 2
  # - platform: "integration"
  #   source: "sensor.sdm220_modbus_current_system_reverse_power_demand"
  #   name: "sdm220_modbus_current_system_reverse_energy_demand"
  #   unique_id: "sensor.sdm220_modbus_current_system_reverse_energy_demand"
  #   unit_prefix: "k"
  #   round: 2
  # - platform: "integration"
  #   source: "sensor.sdm220_modbus_active_power"
  #   name: "sdm220_modbus_active_energy"
  #   unique_id: "sensor.sdm220_modbus_active_energy"
  #   unit_prefix: "k"
  #   round: 2
  # plugs
  # - platform: "integration"
  #   source: "sensor.zigbee_plug_dishwasher_power"
  #   name: "zigbee_plug_dishwasher_current_energy"
  #   unique_id: "sensor.zigbee_plug_dishwasher_current_energy"
  #   unit_prefix: "k"
  #   round: 2
  # - platform: "integration"
  #   source: "sensor.zigbee_plug_washing_machine_power"
  #   name: "zigbee_plug_washing_machine_current_energy"
  #   unique_id: "sensor.zigbee_plug_washing_machine_current_energy"
  #   unit_prefix: "k"
  #   round: 2
  # smart meter
  - platform: "integration"
    source: "sensor.smart_meter_electricity_power"
    name: "smart_meter_electricity_energy"
    unique_id: "sensor.smart_meter_electricity_energy"
    # unit_prefix: "k"
    round: 2
  # Unifi
  - platform: "integration"
    source: "sensor.usw_pro_24_poe_bed_a_laptop_poe_power"
    name: "usw_pro_24_poe_bed_a_laptop_poe_energy"
    unique_id: "sensor.usw_pro_24_poe_bed_a_laptop_poe_energy"
    unit_prefix: "k"
    round: 2
  - platform: "integration"
    source: "sensor.usw_pro_24_poe_bed_a_tv_poe_power"
    name: "usw_pro_24_poe_bed_a_tv_poe_energy"
    unique_id: "sensor.usw_pro_24_poe_bed_a_tv_poe_energy"
    unit_prefix: "k"
    round: 2
  - platform: "integration"
    source: "sensor.usw_pro_24_poe_bed_b_poe_power"
    name: "usw_pro_24_poe_bed_b_poe_energy"
    unique_id: "sensor.usw_pro_24_poe_bed_b_poe_energy"
    # unit_prefix: "k"
    round: 2
  - platform: "integration"
    source: "sensor.usw_pro_24_poe_kitchen_poe_power"
    name: "usw_pro_24_poe_kitchen_poe_energy"
    unique_id: "sensor.usw_pro_24_poe_kitchen_poe_energy"
    # unit_prefix: "k"
    round: 2
  - platform: "integration"
    source: "sensor.usw_pro_24_poe_loft_poe_power"
    name: "usw_pro_24_poe_loft_poe_energy"
    unique_id: "sensor.usw_pro_24_poe_loft_poe_energy"
    # unit_prefix: "k"
    round: 2
  - platform: "integration"
    source: "sensor.usw_pro_24_poe_lounge_right_poe_power"
    name: "usw_pro_24_poe_lounge_right_poe_energy"
    unique_id: "sensor.usw_pro_24_poe_lounge_right_poe_energy"
    # unit_prefix: "k"
    round: 2
  - platform: "integration"
    source: "sensor.usw_pro_24_poe_study_poe_power"
    name: "usw_pro_24_poe_study_poe_energy"
    unique_id: "sensor.usw_pro_24_poe_study_poe_energy"
    # unit_prefix: "k"
    round: 2

  - platform: "integration"
    source: "sensor.usw_flex_loft_ap_top_poe_power"
    name: "usw_flex_loft_ap_top_poe_energy"
    unique_id: "sensor.usw_flex_loft_ap_top_poe_energy"
    # unit_prefix: "k"
    round: 2
  - platform: "integration"
    source: "sensor.usw_flex_loft_cam_back_poe_power"
    name: "usw_flex_loft_cam_back_poe_energy"
    unique_id: "sensor.usw_flex_loft_cam_back_poe_energy"
    # unit_prefix: "k"
    round: 2
  - platform: "integration"
    source: "sensor.usw_flex_loft_cam_front_poe_power"
    name: "usw_flex_loft_cam_front_poe_energy"
    unique_id: "sensor.usw_flex_loft_cam_front_poe_energy"
    # unit_prefix: "k"
    round: 2
  - platform: "integration"
    source: "sensor.usw_flex_loft_dlpc_isolated_poe_power"
    name: "usw_flex_loft_dlpc_isolated_poe_energy"
    unique_id: "sensor.usw_flex_loft_dlpc_isolated_poe_energy"
    # unit_prefix: "k"
    round: 2

  - platform: "integration"
    source: "sensor.usw_lite_8port_bed_e_g3_flex_hall_poe_power"
    name: "usw_lite_8port_bed_e_g3_flex_hall_poe_energy"
    unique_id: "sensor.usw_lite_8port_bed_e_g3_flex_hall_poe_energy"
    # unit_prefix: "k"
    round: 2

# sensor.amazon_firestick_4k_rj45_unifi_tx_2
# sensor.amazon_firestick_4k_rj45_unifi_tx
# sensor.apple_imac_2011_unifi_tx
# sensor.apple_macbook_pro_2018_kev_unifi_tx
# sensor.apple_tv_4k_unifi_tx
# sensor.arcade_machine_unifi_tx
# sensor.big_pc_unifi_tx
# sensor.caldigit_thunderbolt_dock_unifi_tx
# sensor.dans_nintendo_switch_unifi_tx
# sensor.dell_work_laptop_kev_unifi_wifi_tx
# sensor.download_pc_unifi_tx
# sensor.ipad_air_4th_gen_tx
# sensor.kev_iphone_11_unifi_tx
# sensor.home_assistant_unifi_tx
# sensor.iphone_12_dan_tx
# sensor.iphone_tx_4
# sensor.ju_iphone_8_unifi_tx
# sensor.samsung_ue32f4500_tv_unifi_tx
# sensor.samsung_ue48hu7500t_tv_unifi_tx
# sensor.sony_playstation_3_unifi_tx
# sensor.synology_diskstation_ds412_unifi_tx
# sensor.xbox_series_x_unifi_tx

# sensor.usw_flex_loft_dlpc_isolated_poe_power
# sensor.usw_flex_loft_ap_top_poe_power
# sensor.usw_pro_24_poe_bed_a_laptop_poe_power
# sensor.usw_pro_24_poe_bed_a_tv_poe_power
# sensor.usw_pro_24_poe_bed_b_poe_power
# sensor.usw_pro_24_poe_kitchen_poe_power
# sensor.usw_pro_24_poe_loft_poe_power
# sensor.usw_pro_24_poe_lounge_right_poe_power
# sensor.usw_pro_24_poe_study_poe_power
