---
sensor:

  - platform: "statistics"
    entity_id: "sensor.nvidia_shield_lounge_unifi_tx"
    unique_id: "nvidia_shield_lounge_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.nvidia_shield_bed_e_unifi_tx"
    unique_id: "nvidia_shield_bed_e_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.amazon_firestick_4k_rj45_unifi_tx_2"
    unique_id: "amazon_firestick_4k_rj45_unifi_tx_2_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.amazon_firestick_4k_rj45_unifi_tx"
    unique_id: "amazon_firestick_4k_rj45_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.apple_imac_2011_unifi_tx"
    unique_id: "apple_imac_2011_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.apple_macbook_pro_2018_kev_unifi_tx"
    unique_id: "apple_macbook_pro_2018_kev_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.apple_tv_4k_unifi_tx"
    unique_id: "apple_tv_4k_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.arcade_machine_unifi_tx"
    unique_id: "arcade_machine_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.big_pc_unifi_tx"
    unique_id: "big_pc_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.caldigit_thunderbolt_dock_unifi_tx"
    unique_id: "caldigit_thunderbolt_dock_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.dans_nintendo_switch_unifi_tx"
    unique_id: "dans_nintendo_switch_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.dell_work_laptop_kev_unifi_wifi_tx"
    unique_id: "dell_work_laptop_kev_unifi_wifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.download_pc_unifi_tx"
    unique_id: "download_pc_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.ipad_air_4th_gen_tx"
    unique_id: "ipad_air_4th_gen_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.kev_iphone_11_unifi_tx"
    unique_id: "kev_iphone_11_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.home_assistant_unifi_tx"
    unique_id: "home_assistant_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.iphone_12_dan_tx"
    unique_id: "iphone_12_dan_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.iphone_tx_4"
    unique_id: "iphone_tx_4_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.ju_iphone_8_unifi_tx"
    unique_id: "ju_iphone_8_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.samsung_ue32f4500_tv_unifi_tx"
    unique_id: "samsung_ue32f4500_tv_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.samsung_ue48hu7500t_tv_unifi_tx"
    unique_id: "samsung_ue48hu7500t_tv_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.sony_playstation_3_unifi_tx"
    unique_id: "sony_playstation_3_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.synology_diskstation_ds412_unifi_tx"
    unique_id: "synology_diskstation_ds412_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  - platform: "statistics"
    entity_id: "sensor.xbox_series_x_unifi_tx"
    unique_id: "xbox_series_x_unifi_tx_data_speed"
    state_characteristic: "mean"
    sampling_size: 5

  # kitchen
  - platform: "integration"
    source: "sensor.zigbee_energy_outlet_switch_washing_machine_switch_power"
    name: "washing_machine_plug_total_increasing_energy"
    unique_id: "sensor.washing_machine_plug_total_increasing_energy"
    round: 2
  - platform: "integration"
    source: "sensor.zigbee_energy_outlet_switch_dishwasher_switch_power"
    name: "dishwasher_plug_total_increasing_energy"
    unique_id: "sensor.dishwasher_plug_total_increasing_energy"
    round: 2
  # Unifi
  - platform: "integration"
    source: "sensor.usw_pro_24_poe_bed_a_laptop_poe_power"
    name: "usw_pro_24_poe_bed_a_laptop_poe_energy"
    unique_id: "sensor.usw_pro_24_poe_bed_a_laptop_poe_energy"
    unit_prefix: "k"
    round: 2
  - platform: "integration"
    source: "sensor.usw_pro_24_poe_bed_a_tv_poe_power"
    name: "usw_pro_24_poe_bed_a_tv_poe_energy"
    unique_id: "sensor.usw_pro_24_poe_bed_a_tv_poe_energy"
    unit_prefix: "k"
    round: 2
  - platform: "integration"
    source: "sensor.usw_pro_24_poe_bed_b_poe_power"
    name: "usw_pro_24_poe_bed_b_poe_energy"
    unique_id: "sensor.usw_pro_24_poe_bed_b_poe_energy"
    round: 2
  - platform: "integration"
    source: "sensor.usw_pro_24_poe_kitchen_poe_power"
    name: "usw_pro_24_poe_kitchen_poe_energy"
    unique_id: "sensor.usw_pro_24_poe_kitchen_poe_energy"
    round: 2
  - platform: "integration"
    source: "sensor.usw_pro_24_poe_loft_poe_power"
    name: "usw_pro_24_poe_loft_poe_energy"
    unique_id: "sensor.usw_pro_24_poe_loft_poe_energy"
    round: 2
  - platform: "integration"
    source: "sensor.usw_pro_24_poe_lounge_right_poe_power"
    name: "usw_pro_24_poe_lounge_right_poe_energy"
    unique_id: "sensor.usw_pro_24_poe_lounge_right_poe_energy"
    round: 2
  - platform: "integration"
    source: "sensor.usw_pro_24_poe_study_poe_power"
    name: "usw_pro_24_poe_study_poe_energy"
    unique_id: "sensor.usw_pro_24_poe_study_poe_energy"
    round: 2

  - platform: "integration"
    source: "sensor.usw_flex_loft_ap_top_poe_power"
    name: "usw_flex_loft_ap_top_poe_energy"
    unique_id: "sensor.usw_flex_loft_ap_top_poe_energy"
    round: 2
  - platform: "integration"
    source: "sensor.usw_flex_loft_cam_back_poe_power"
    name: "usw_flex_loft_cam_back_poe_energy"
    unique_id: "sensor.usw_flex_loft_cam_back_poe_energy"
    round: 2
  - platform: "integration"
    source: "sensor.usw_flex_loft_cam_front_poe_power"
    name: "usw_flex_loft_cam_front_poe_energy"
    unique_id: "sensor.usw_flex_loft_cam_front_poe_energy"
    round: 2
  - platform: "integration"
    source: "sensor.usw_flex_loft_dlpc_isolated_poe_power"
    name: "usw_flex_loft_dlpc_isolated_poe_energy"
    unique_id: "sensor.usw_flex_loft_dlpc_isolated_poe_energy"
    round: 2

  - platform: "integration"
    source: "sensor.usw_lite_8port_bed_e_g3_flex_hall_poe_power"
    name: "usw_lite_8port_bed_e_g3_flex_hall_poe_energy"
    unique_id: "sensor.usw_lite_8port_bed_e_g3_flex_hall_poe_energy"
    # unit_prefix: "k"
    round: 2

  # TP 110 plugs
  - platform: "integration"
    source: "sensor.fridge_plug_kitchen_current_power"
    name: "Fridge Plug Energy:Kitchen"
    unique_id: "sensor.kitchen_fridge_total_increasing_energy"
    # unit_prefix: "k"
    round: 2
  - platform: "integration"
    source: "sensor.kettle_plug_kitchen_current_power"
    name: "Kettle Plug Energy:Kitchen"
    unique_id: "sensor.kitchen_kettle_total_increasing_energy"
    # unit_prefix: "k"
    round: 2
  - platform: "integration"
    source: "sensor.microwave_plug_kitchen_current_power"
    name: "Microwave Plug Energy:Kitchen"
    unique_id: "sensor.kitchen_microwave_total_increasing_energy"
    # unit_prefix: "k"
    round: 2
  - platform: "integration"
    source: "sensor.chest_freezer_plug_garage_current_power"
    name: "Chest Freezer Plug Energy:Garage"
    unique_id: "sensor.garage_chest_freezer_total_increasing_energy"
    # unit_prefix: "k"
    round: 2
  - platform: "integration"
    source: "sensor.fridge_freezer_plug_garage_current_power"
    name: "Fridge/Freezer Plug Energy:Garage"
    unique_id: "sensor.garage_fridgefreezer_total_increasing_energy"
    # unit_prefix: "k"
    round: 2
  - platform: "integration"
    source: "sensor.drinks_fridge_plug_bed_c_current_power"
    name: "Drinks Fridge Plug Energy:Bed C"
    unique_id: "sensor.bed_c_drinks_fridge_total_increasing_energy"
    # unit_prefix: "k"
    round: 2
  - platform: "integration"
    source: "sensor.udm_pro_plug_bed_c_current_power"
    name: "UDM Pro Plug Energy:Bed C"
    unique_id: "sensor.bed_c_udm_pro_total_increasing_energy"
    # unit_prefix: "k"
    round: 2
  - platform: "integration"
    source: "sensor.table_lamp_plug_lounge_current_power"
    name: "Table Lamp Plug Energy:Lounge"
    unique_id: "sensor.lounge_table_lamp_total_increasing_energy"
    # unit_prefix: "k"
    round: 2

# - platform: "command_line"
#   name: "TP-Link Powerline Adapter"
#   command: "bash scripts/homeplug.sh"

# # SNMP IFTable Sensors
#   - platform: "snmp"
#     host: "192.168.1.40"
#     baseoid: "1.3.6.1.2.1.2.1"
#     name: ""
#     unique_id: ""

# sensor.amazon_firestick_4k_rj45_unifi_tx_2
# sensor.amazon_firestick_4k_rj45_unifi_tx
# sensor.apple_imac_2011_unifi_tx
# sensor.apple_macbook_pro_2018_kev_unifi_tx
# sensor.apple_tv_4k_unifi_tx
# sensor.arcade_machine_unifi_tx
# sensor.big_pc_unifi_tx
# sensor.caldigit_thunderbolt_dock_unifi_tx
# sensor.dans_nintendo_switch_unifi_tx
# sensor.dell_work_laptop_kev_unifi_wifi_tx
# sensor.download_pc_unifi_tx
# sensor.ipad_air_4th_gen_tx
# sensor.kev_iphone_11_unifi_tx
# sensor.home_assistant_unifi_tx
# sensor.iphone_12_dan_tx
# sensor.iphone_tx_4
# sensor.ju_iphone_8_unifi_tx
# sensor.samsung_ue32f4500_tv_unifi_tx
# sensor.samsung_ue48hu7500t_tv_unifi_tx
# sensor.sony_playstation_3_unifi_tx
# sensor.synology_diskstation_ds412_unifi_tx
# sensor.xbox_series_x_unifi_tx

# sensor.usw_flex_loft_dlpc_isolated_poe_power
# sensor.usw_flex_loft_ap_top_poe_power
# sensor.usw_pro_24_poe_bed_a_laptop_poe_power
# sensor.usw_pro_24_poe_bed_a_tv_poe_power
# sensor.usw_pro_24_poe_bed_b_poe_power
# sensor.usw_pro_24_poe_kitchen_poe_power
# sensor.usw_pro_24_poe_loft_poe_power
# sensor.usw_pro_24_poe_lounge_right_poe_power
# sensor.usw_pro_24_poe_study_poe_power
