binary_sensor:
#   - platform: template
#     sensors:
#       yamaha_reciever_state:
#         friendly_name: "Yamaha Reciever State"
#         unique_id: devicetracker_yamaha_reciever_state
#         value_template: "{{ is_state('media_player.rx_v777_reciever_yamaha_integration_bed_c', 'on') }}"
#         icon_template: mdi:audio-video

  # - platform: template
  #   sensors:
  #     back_door_light_on_by_switch:
  #       friendly_name: "Back door light turned on with switch"
  #       unique_id: devicetracker_back_door_light_on_by_switch
  #       icon_template: mdi:light-switch
  #       value_template: >-
  #         {% if states('sensor.vpn_tun0_out_octets_mbps_stats_calc') == 'unknown' or 
  #         states('sensor.vpn_tun0_out_octets_mbps_stats_calc') == 'unavailable' %}
  #           {{ 0 }}
  #         {% else %}
  #           {{ state_attr('sensor.vpn_tun0_out_octets_mbps_stats_calc', 'max_value') }}
  #         {% endif %}

  # - platform: template
  #   sensors:
  #     binary_open_alert_front_door_five_mins:
  #       device_class: opening
  #       friendly_name: "Front Door opened within last 5 minutes"
  #       unique_id: binary_open_alert_front_door_five_mins
  #       value_template: >-
  #         {% set lastTrigger_frontDoor =  as_timestamp(now()) - as_timestamp(states.binary_sensor.zigbee_door_sensor_front_contact.last_changed) %}
  #         {% set previousStateIsOpen_frontDoor = not states.binary_sensor.zigbee_door_sensor_front_contact.attributes.contact.old_state %}
  #         {{ lastTrigger_frontDoor | float < 300 and previousStateIsOpen_frontDoor }}
  #       icon_template: mdi:door-closed-lock

  # - platform: template
  #   sensors:
  #     binary_open_alert_back_door_five_mins:
  #       device_class: opening
  #       friendly_name: "Back Door opened within last 5 minutes"
  #       unique_id: binary_open_alert_back_door_five_mins
  #       value_template: >-
  #         {% set lastTrigger_backDoor =  as_timestamp(now()) - as_timestamp(states.binary_sensor.zigbee_door_sensor_back_contact.last_changed) %}
  #         {% set previousStateIsOpen_backDoor = not states.binary_sensor.zigbee_door_sensor_back_contact.attributes.contact.old_state %}
  #         {{ lastTrigger_backDoor | float < 300 and previousStateIsOpen_backDoor }}
  #       icon_template: mdi:door-closed-lock

  # - platform: template
  #   sensors:
  #     binary_ring_alert_doorbell_five_mins:
  #       device_class: sound
  #       friendly_name: "Doorbell rung within last 5 minutes"
  #       unique_id: binary_ring_alert_doorbell_five_mins
  #       value_template: >-
  #         {% set lastTrigger_doorbell = as_timestamp(now()) - as_timestamp(states.binary_sensor.doorbell_uvc_g4_doorbell.attributes.last_tripped_time) %}
  #         {{ lastTrigger_doorbell | float < 300 }}
  #       icon_template: mdi:doorbell-video