---
sensor:
  - platform: "bitcoin"
    currency: "GBP"
    display_options:
      - "exchangerate"
      - "trade_volume_btc"
  # - platform: "otp"
  #   name: "Unifi Auth"
  #   token: !secret "unifi_auth_otp"
  # - platform: "otp"
  #   name: "Amazon Auth"
  #   token: !secret "amazon_auth_otp"
  # - platform: "otp"
  #   name: "Github Auth"
  #   token: !secret "github_auth_otp"
  # - platform: "otp"
  #   name: "FastHosts Auth"
  #   token: !secret "fasthosts_auth_otp"
  - platform: "influxdb"
    database: "unifi"
    username: !secret "hass_addon_influx_db_user"
    password: !secret "hass_addon_influx_db_pass"
    queries:
      - unique_id: "influxdb_unifi_rx_yaml_imported"
        name: "InfluxDB Unifi RX"
        unit_of_measurement: "B/s"
        field: "rx_bytes"
        where: "time > now() - 1d"
        group_function: "last"
        database: "unifi"
        measurement: >
          "unifi"."autogen"."clients"

  - platform: "uk_transport"
    app_id: "734a3e4d"
    app_key: "7392c794ad863f41991ceda8166b279b"
    queries:
      - mode: "train"
        origin: "BAN"
        destination: "GLD"
      - mode: "train"
        origin: "GLD"
        destination: "BAN"

  - platform: "london_underground"
    line:
      - "Bakerloo"
      - "Central"
      - "Circle"
      - "District"
      - "DLR"
      - "Elizabeth line"
      - "Hammersmith & City"
      - "Jubilee"
      - "London Overground"
      - "Metropolitan"
      - "Northern"
      - "Piccadilly"
      - "Victoria"
      - "Waterloo & City"

binary_sensor:
  - platform: "tod"
    name: "nighttime"
    after: "sunset"
    before: "sunrise"
    unique_id: "tod_nighttime"
  - platform: "tod"
    name: "quiettime"
    after: "23:00"
    before: "07:00"
    unique_id: "tod_quiettime"
  - platform: "tod"
    name: "cheap heating time"
    after: "00:00"
    before: "07:00"
    unique_id: "tod_cheap_heating_time"
  - platform: "tod"
    name: "morning heating time"
    after: "06:00"
    before: "09:00"
    unique_id: "tod_morning_heating_time"
  - platform: "tod"
    name: "afternoon heating time"
    after: "14:00"
    before: "17:00"
    unique_id: "tod_afternoon_heating_time"
  - platform: "tod"
    name: "evening heating time"
    after: "19:00"
    before: "21:00"
    unique_id: "tod_evening_heating_time"

spotcast:   #default is home account
  sp_dc: !secret "spotcast_homeaccount_sp_dc"
  sp_key: !secret "spotcast_homeaccount_sp_key"
  accounts:
    kevin:
      sp_dc: !secret "spotcast_kevin_sp_dc"
      sp_key: !secret "spotcast_kevin_sp_key"
    emily:
      sp_dc: !secret "spotcast_emily_sp_dc"
      sp_key: !secret "spotcast_emily_sp_key"

iperf3:
  hosts:
    - host: "iperf.he.net"
    - host: "speedtest-london.its-tg.net"

monitor_docker:
  - name: "Docker"
    url: "tcp://192.168.10.5:2375"

influxdb:
  username: !secret "hass_addon_influx_db_user"
  password: !secret "hass_addon_influx_db_pass"
  exclude:
    domains:
      - "event"
      - "group"
      - "update"

air_quality:
  - platform: "opensensemap"
    station_id: "5faeb5589b2df8001b980304"

emulated_roku:
  servers:
    - name: "Home Assistant"
      listen_port: 8060

      # - automation, binary_sensor, button, calendar, camera, climate, device_tracker,
      # event,
      # fan,
      # group,
      # image, input_boolean, input_datetime, input_select, input_text, lawn_mower,
      # light, lock, media_player, number, person, remote, scene, script, select, sensor, siren, stt,
      # sun, switch, text, tts,
      # update, wake_word, water_heater, weather, zone
