---
# proximity:
#   home:
#     devices:
#       # Kevin
#       - "device_tracker.kev_iphone_11_unifi"
#       - "device_tracker.repl_iphone_11"
#       - "device_tracker.kevin_iphone_ha_app"
#       # Julia
#       - "device_tracker.ju_iphone_8_unifi"
#       - "device_tracker.julia_s_iphone_6"
#       # Daniel
#       - "device_tracker.iphone_12_dan_unifi"
#       - "device_tracker.iphone"
#       # Emily
#       - "device_tracker.iphone_5"
#       - "device_tracker.patrice"
#     tolerance: 50
#     unit_of_measurement: "mi"
#   kevin_thorn_home:
#     zone: "home"
#     devices:
#       - "device_tracker.kev_iphone_11_unifi"
#       - "device_tracker.repl_iphone_11"
#       - "device_tracker.kevin_iphone_ha_app"
#     tolerance: 50
#     unit_of_measurement: "mi"
#   julia_thorn_home:
#     zone: "home"
#     devices:
#       - "device_tracker.ju_iphone_8_unifi"
#       - "device_tracker.julia_s_iphone_6"
#     tolerance: 50
#     unit_of_measurement: "mi"
#   daniel_thorn_home:
#     zone: "home"
#     devices:
#       - "device_tracker.iphone_12_dan"
#       - "device_tracker.iphone"
#     tolerance: 50
#     unit_of_measurement: "mi"
#   daniel_thorn_uni:
#     zone: "dan_uni_accomodation"
#     devices:
#       - "device_tracker.iphone_12_dan"
#       - "device_tracker.iphone"
#     tolerance: 50
#     unit_of_measurement: "mi"
#   emily_thorn_home:
#     zone: "home"
#     devices:
#       - "device_tracker.iphone_5"
#       - "device_tracker.patrice"
#     tolerance: 50
#     unit_of_measurement: "mi"
sensor:
  # - platform: "tautulli"
  #   name: "Plex State Tautulli"
  #   host: !secret "ha_rj45_ip"
  #   api_key: !secret "tautulli_api_key"

  - platform: "bitcoin"
    currency: "GBP"
    display_options:
      - "exchangerate"
      - "trade_volume_btc"

  - platform: "otp"
    name: "Unifi Auth"
    token: !secret "unifi_auth_otp"
  - platform: "otp"
    name: "Amazon Auth"
    token: !secret "amazon_auth_otp"
  - platform: "otp"
    name: "Github Auth"
    token: !secret "github_auth_otp"
  - platform: "otp"
    name: "FastHosts Auth"
    token: !secret "fasthosts_auth_otp"

  - platform: "uk_transport"
    app_id: "734a3e4d"
    app_key: "7392c794ad863f41991ceda8166b279b"
    queries:
      - mode: "train"
        origin: "BAN"
        destination: "RDG" # "GLD"

binary_sensor:
  - platform: "tod"
    name: "nighttime"
    after: "sunset"
    before: "sunrise"
    unique_id: "tod_nighttime"
  - platform: "tod"
    name: "quiettime"
    after: "23:00"
    before: "07:00"
    unique_id: "tod_quiettime"
  - platform: "tod"
    name: "cheap heating time"
    after: "00:00"
    before: "07:00"
    unique_id: "tod_cheap_heating_time"
  - platform: "tod"
    name: "morning heating time"
    after: "06:00"
    before: "09:00"
    unique_id: "tod_morning_heating_time"
  - platform: "tod"
    name: "afternoon heating time"
    after: "14:00"
    before: "17:00"
    unique_id: "tod_afternoon_heating_time"
  - platform: "tod"
    name: "evening heating time"
    after: "19:00"
    before: "21:00"
    unique_id: "tod_evening_heating_time"
# influxdb:
#   host: 192.168.1.22
#   database: unifi
#   username: !secret "influx_db_user"
#   password: !secret "influx_db_pass"
#   max_retries: 3
#   default_measurement: "state"
#   exclude:
#     entities:
#        - entity.id1
#        - entity.id2
#     domains:
#        - automation
#   include:
#     entities:
#        - entity.id3
#        - entity.id4
#   tags:
#     instance: prod
#     source: hass
