---
# ingress:
  # convertx_addin:
  # it_tools_addin:
  # moodist_addin:
  # overseerr_addin:
  # plex_addin:
  # uptime_kuma_addin:
  # unifi_local:
  #   work_mode: "iframe"
  #   ui_mode: "normal"
  #   title: "Unifi"
  #   icon: "mdi:router-network"
  #   url: "https://unifi.ui.com/"

ingress:
  tabs_development:
    work_mode: "custom" # MUST
    url: "/files/ingress/ha-tabs-ingress.js" # MUST
    title: "Dev Add-ins"
    ui_mode: "replace"
    icon: "mdi:application-braces"
  esphome:
    parent: "tabs_development"
    work_mode: "hassio"
    title: "ESPHome"
    icon: "simple-icons:esphome"
    url: !secret "hass_addon_esphome_docker_slug"
  studio_code_server:
    parent: "tabs_development"
    work_mode: "hassio"
    title: "VS Code"
    icon: "simple-icons:coder"
    url: !secret "hass_addon_studiocodeserver_docker_slug"
  hacs:
    parent: "tabs_development"
    work_mode: "iframe"
    ui_mode: "toolbar"
    title: "HACS"
    icon: "simple-icons:homeassistantcommunitystore"
    url: "/hacs/dashboard"
  # hacsproxy:
  #   parent: "tabs_development"
  #   work_mode: "ingress"
  #   ui_mode: "normal"
  #   title: "HACS"
  #   icon: "simple-icons:homeassistantcommunitystore"
  #   url: "/api/ingress/hacsredirect"
  #   static_token: !secret "ha_statuc_key_hacs_ingress"
  #   headers:
  #     authorization: !secret "ha_statuc_key_hacs_ingress"
  netalertx:
    parent: "tabs_development"
    work_mode: "hassio"
    title: "NetAlertX"
    url: !secret "hass_addon_netdata_docker_slug"
  it_tools:
    parent: "tabs_development"
    title: "IT-Tools"
    url: !secret "hass_addon_it_tools_webui_local_url"
    headers:
      X-Script-Name: $http_x_ingress_path
      Origin: $auto
    rewrite:
      # fix no directory REST links
      - mode: "body"
        match: href="/*([\S]+)"
        replace: href="$http_x_ingress_path/\1"
      - mode: "body"
        match: src="/*([\S]+)"
        replace: src="$http_x_ingress_path/\1"
      # rewrite root files
      - mode: "body"
        match: \/sw.js
        replace: $http_x_ingress_path/sw.js
      # MIME type correction (if needed for CSS/JS responses)
      - mode: "header"
        path: \.css$
        name: "Content-Type"
        match: "text/plain"
        replace: "text/css"
  cyberchef:
    parent: "tabs_development"
    work_mode: "hassio"
    title: "CyberChef"
    url: !secret "hass_addon_cyberchef_docker_slug"
  convertx:
    parent: "tabs_development"
    title: "ConvertX"
    url: !secret "hass_addon_convertx_webui_local_url"
    rewrite:
      - mode: "body"
        match: href="/"
        replace: href="$http_x_ingress_path/"
      - mode: "body"
        match: href="/history"
        replace: href="$http_x_ingress_path/history"
      # rewrite root files
      - mode: "body"
        match: \/generated.css
        replace: $http_x_ingress_path/generated.css
  my_ip:
    parent: "tabs_development"
    title: "My-IP"
    url: !secret "hass_addon_myip_webui_local_url"



  tabs_admin:
    work_mode: "custom" # MUST
    url: "/files/ingress/ha-tabs-ingress.js" # MUST
    title: "Admin Add-ins"
    icon: "mdi:account-wrench"
  guacamole:
    parent: "tabs_admin"
    work_mode: "hassio"
    title: "Guacamole"
    icon: "simple-icons:apacheguacamole"
    url: !secret "hass_addon_guacamole_docker_slug"
  portainer:
    parent: "tabs_admin"
    work_mode: "hassio"
    title: "Portainer"
    icon: "simple-icons:portainer"
    url: !secret "hass_addon_portainer_docker_slug"
  phpmyadmin:
    parent: "tabs_admin"
    work_mode: "hassio"
    title: "phpMyAdmin"
    icon: "simple-icons:phpmyadmin"
    url: !secret "hass_addon_phpmyadmin_docker_slug"
  advanced_ssh:
    parent: "tabs_admin"
    work_mode: "hassio"
    title: "SSH"
    icon: "mdi:ssh"
    url: !secret "hass_addon_advanced_ssh_docker_slug"
  adguard:
    parent: "tabs_admin"
    work_mode: "hassio"
    title: "AdGuard"
    icon: "simple-icons:adguard"
    url: !secret "hass_addon_adguard_docker_slug"
  browser_mod:
    parent: "tabs_admin"
    work_mode: "iframe"
    # ui_mode: "replace"
    title: "Browser Mod"
    url: "/browser-mod"
  # nginx_proxy_manager:
  #   parent: "tabs_admin"
  #   title: "Nginx Proxy Manager"
  #   icon: "simple-icons:nginxproxymanager"
  #   url: "http://127.0.0.1:81"



  tabs_diagnostics:
    work_mode: "custom" # MUST
    url: "/files/ingress/ha-tabs-ingress.js" # MUST
    title: "Diagnostic Add-ins"
    icon: "mdi:stethoscope"
  uptime_kuma:
    parent: "tabs_diagnostics"
    title: "Uptime Kuma"
    icon: "simple-icons:uptimekuma"
    url: !secret "hass_addon_uptime_kuma_webui_local_url"
    index: "/dashboard"
    rewrite:
    # Fix HTML asset references
      - mode: body
        path:  /.*
        match: '((?:href|src|action|data|poster|srcset)=")(/(?!api/ingress|http)[^"]+)(")'
        replace: "\\1$http_x_ingress_path\\2\\3"

      # Fix CSS url() - separate pattern to preserve url(
      - mode: body
        path: /.*
        match: "(url\\()(['\"]?)(/(?!api/ingress|http)[^'\")]+)(\\2)(\\))"
        replace: "\\1\\2$http_x_ingress_path\\3\\4\\5"
      # - mode: "body"
      #   match: href="/*([\S]+)"
      #   replace: href="$http_x_ingress_path/\1"
      # - mode: "body"
      #   match: src="/*([\S]+)"
      #   replace: src="$http_x_ingress_path/\1"
      # - mode: "body"
      #   match: data="/*([\S]+)"
      #   replace: data="$http_x_ingress_path/\1"
      # - mode: "body"
      #   match: (/socket\.io/)
      #   replace: /$http_x_ingress_path/\1/
      # - mode: "header"
      #   match: /(socket\.io)/
      #   replace: /$http_x_ingress_path/\1/
  emqx:
    parent: "tabs_diagnostics"
    work_mode: "hassio"
    title: "EMQX"
    icon: "simple-icons:mqtt"
    url: !secret "hass_addon_emqx_docker_slug"
  scrutiny:
    parent: "tabs_diagnostics"
    work_mode: "hassio"
    title: "Scrutiny (Full Access)"
    icon: "mdi:glasses"
    url: !secret "hass_addon_scrutinyfa_docker_slug"
  influxdb:
    parent: "tabs_diagnostics"
    work_mode: "hassio"
    title: "InfluxDB"
    icon: "simple-icons:influxdb"
    url: !secret "hass_addon_influx_db_docker_slug"
  grafana:
    parent: "tabs_diagnostics"
    work_mode: "hassio"
    title: "Grafana"
    icon: "simple-icons:grafana"
    url: !secret "hass_addon_grafana_docker_slug"
  matter_server:
    parent: "tabs_diagnostics"
    work_mode: "hassio"
    title: "Matter Server"
    icon: "m3of:matter"
    url: !secret "hass_addon_matterserver_docker_slug"
  # matterbridge:
  #   parent: "tabs_diagnostics"
  #   work_mode: "hassio"
  #   title: "MatterBridge"
  #   icon: "simple-icons:homebridge"
  #   url: "246dd49f_matterbridge"
  # netdata:
  #   parent: "tabs_diagnostics"
  #   work_mode: "hassio"
  #   title: "Netdata"
  #   icon: "simple-icons:netdata"
  #   url: "47146a2b_netdata"



  tabs_media:
    work_mode: "custom" # MUST
    url: "/files/ingress/ha-tabs-ingress.js" # MUST
    title: "Media Add-ins"
    icon: "mdi:multimedia"
  music_assistant_server:
    parent: "tabs_media"
    work_mode: "hassio"
    title: "Music Assistant Server"
    url: !secret "hass_addon_musicassistantserver_docker_slug"
  media_browser:
    parent: "tabs_media"
    work_mode: "iframe"
    # ui_mode: "replace"
    title: "Media Browser"
    url: "/media-browser/browser"
  moodist:
    parent: "tabs_media"
    title: "Moodist"
    url: !secret "hass_addon_monica_webui_local_url"
    rewrite:
      # rewrite folders
      - mode: "body"
        match: /(_astro|fonts|sounds)/
        replace: $http_x_ingress_path/\1/
      # rewrite logo
      - mode: "body"
        match: \/logo.svg
        replace: $http_x_ingress_path/logo.svg
      # rewrite root files
      - mode: "body"
        match: \/sw.js
        replace: $http_x_ingress_path/sw.js
      - mode: "body"
        match: \/logo-light.png
        replace: $http_x_ingress_path/logo-light.png
      # MIME type correction (if needed for CSS/JS responses)
      - mode: "header"
        path: \.css$
        name: "Content-Type"
        match: "text/plain"
        replace: "text/css"
  5etools:
    parent: "tabs_media"
    work_mode: "hassio"
    title: "5e Tools"
    icon: "simple-icons:dungeonsanddragons"
    url: !secret "hass_addon_5etools_docker_slug"
  calibre_web:
    parent: "tabs_media"
    work_mode: "hassio"
    title: "Calibre Web"
    url: !secret "hass_addon_calibre_docker_slug"



  tabs_organisation:
    work_mode: "custom" # MUST
    url: "/files/ingress/ha-tabs-ingress.js" # MUST
    title: "Organisation Add-ins"
    icon: "simple-icons:openmediavault"
  ha_map:
    parent: "tabs_organisation"
    work_mode: "iframe"
    title: "Map"
    url: "/map"
  ha_logbook:
    parent: "tabs_organisation"
    work_mode: "iframe"
    title: "Logbook"
    url: "/logbook"
  ha_history:
    parent: "tabs_organisation"
    work_mode: "iframe"
    title: "History"
    url: "/history"
  ha_calendar:
    parent: "tabs_organisation"
    work_mode: "iframe"
    title: "Calendar"
    url: "/calendar"
  ha_todo:
    parent: "tabs_organisation"
    work_mode: "iframe"
    title: "ToDo"
    url: "/todo"
  homebox:
    parent: "tabs_organisation"
    title: "Homebox"
    url: !secret "hass_addon_homebox_webui_local_url"
  ha_home_maintenance:
    parent: "tabs_organisation"
    work_mode: "iframe"
    title: "Home Maintenance"
    url: "/home-maintenance"
  monica:
    parent: "tabs_organisation"

    title: "Monica"
    url: !secret "hass_addon_monica_webui_local_url"

  openproject:
    parent: "tabs_organisation"
    title: "Open Project"
    url: !secret "hass_addon_openproject_webui_local_url"
  silverbullet:
    parent: "tabs_organisation"
    title: "Silver Bullet"
    url: !secret "hass_addon_silverbullet_webui_local_url"


  svc_5etools:
    work_mode: "ingress"
    ui_mode: "normal"
    title: "5etools"
    url: !secret "hass_addon_5etools_docker_slug"
    static_token: !secret "hass_addon_5etools_webui_static_token"
  svc_adguard:
    work_mode: "ingress"
    ui_mode: "normal"
    title: "adguard"
    url: !secret "hass_addon_adguard_docker_slug"
    static_token: !secret "hass_addon_adguard_webui_static_token"
  svc_advanced_ssh:
    work_mode: "ingress"
    ui_mode: "normal"
    title: "advanced_ssh"
    url: !secret "hass_addon_advanced_ssh_docker_slug"
    static_token: !secret "hass_addon_advanced_ssh_webui_static_token"
  svc_calibre:
    work_mode: "ingress"
    ui_mode: "normal"
    title: "calibre"
    url: !secret "hass_addon_calibre_docker_slug"
    static_token: !secret "hass_addon_calibre_webui_static_token"
  svc_cyberchef:
    work_mode: "ingress"
    ui_mode: "normal"
    title: "cyberchef"
    url: !secret "hass_addon_cyberchef_docker_slug"
    static_token: !secret "hass_addon_cyberchef_webui_static_token"
  svc_emqx:
    work_mode: "ingress"
    ui_mode: "normal"
    title: "emqx"
    url: !secret "hass_addon_emqx_docker_slug"
    static_token: !secret "hass_addon_emqx_webui_static_token"
  svc_esphome:
    work_mode: "ingress"
    ui_mode: "normal"
    title: "ESPHome"
    url: !secret "hass_addon_esphome_docker_slug"
    static_token: !secret "hass_addon_esphome_webui_static_token"
  svc_grafana:
    work_mode: "ingress"
    ui_mode: "normal"
    title: "grafana"
    url: !secret "hass_addon_grafana_docker_slug"
    static_token: !secret "hass_addon_grafana_webui_static_token"
  svc_guacamole:
    work_mode: "ingress"
    ui_mode: "normal"
    title: "guacamole"
    url: !secret "hass_addon_guacamole_docker_slug"
    static_token: !secret "hass_addon_guacamole_webui_static_token"
  svc_influx_db:
    work_mode: "ingress"
    ui_mode: "normal"
    title: "influx_db"
    url: !secret "hass_addon_influx_db_docker_slug"
    static_token: !secret "hass_addon_influx_db_webui_static_token"
  svc_matterserver:
    work_mode: "ingress"
    ui_mode: "normal"
    title: "matterserver"
    url: !secret "hass_addon_matterserver_docker_slug"
    static_token: !secret "hass_addon_matterserver_webui_static_token"
  svc_matterbridge:
    work_mode: "ingress"
    ui_mode: "normal"
    title: "matterbridge"
    url: !secret "hass_addon_matterbridge_docker_slug"
    static_token: !secret "hass_addon_matterbridge_webui_static_token"
  svc_musicassistantserver:
    work_mode: "ingress"
    ui_mode: "normal"
    title: "musicassistantserver"
    url: !secret "hass_addon_musicassistantserver_docker_slug"
    static_token: !secret "hass_addon_musicassistantserver_webui_static_token"
  svc_netalertx:
    work_mode: "ingress"
    ui_mode: "normal"
    title: "netalertx"
    url: !secret "hass_addon_netalertx_docker_slug"
    static_token: !secret "hass_addon_netalertx_webui_static_token"
  svc_netdata:
    work_mode: "ingress"
    ui_mode: "normal"
    title: "netdata"
    url: !secret "hass_addon_netdata_docker_slug"
    static_token: !secret "hass_addon_netdata_webui_static_token"
  svc_node_red:
    work_mode: "ingress"
    ui_mode: "normal"
    title: "node_red"
    url: !secret "hass_addon_node_red_docker_slug"
    static_token: !secret "hass_addon_node_red_webui_static_token"
  svc_phpmyadmin:
    work_mode: "ingress"
    ui_mode: "normal"
    title: "phpmyadmin"
    url: !secret "hass_addon_phpmyadmin_docker_slug"
    static_token: !secret "hass_addon_phpmyadmin_webui_static_token"
  svc_portainer:
    work_mode: "ingress"
    ui_mode: "normal"
    title: "portainer"
    url: !secret "hass_addon_portainer_docker_slug"
    static_token: !secret "hass_addon_portainer_webui_static_token"
  svc_scrutinyfa:
    work_mode: "ingress"
    ui_mode: "normal"
    title: "scrutinyfa"
    url: !secret "hass_addon_scrutinyfa_docker_slug"
    static_token: !secret "hass_addon_scrutinyfa_webui_static_token"
  svc_studiocodeserver:
    work_mode: "ingress"
    ui_mode: "normal"
    title: "scrutinyfa"
    url: !secret "hass_addon_studiocodeserver_docker_slug"
    static_token: !secret "hass_addon_studiocodeserver_webui_static_token"